.travis.yml
README.md
common/cron/cron_test.go
etc/conf/app.conf
scripts/prepare_env_ut.sh
scripts/ut.sh

Updated the UT configuration for Service Center
Note: After this pull requests is merged please enable the service-center project in https://coveralls.io and change the link in the Readme.md

JAV-14 Updated Coverage Configuration

---

etc/conf/app.conf
server/service/microservices.go

1. Fix dead lock bug when call quota api failed.
2. Adjust max bytes limit of request body

Dead lock bug fixed and adjust max limit of request body

---

scripts/docker/build-image/Dockerfile.tmpl
scripts/docker/build-image/README.md
scripts/docker/build-image/build.sh
scripts/docker/build-image/start.sh

1. Run build.sh script inside scripts/docker/buid-image path.
2. It will build the service-center executable and copy the binary in the etcd base image and creates new image tar.
3. load the tar to the docker and run the image. Your service-center will be running with your new modifications if any.

Support docker-compose for building the project

---

server/plugin/infra/registry/etcd/etcd.go
server/server.go
server/service/instances.go

Because the etcd will change to be unavailable when the defragment is in progress.

SCB-129 Do not defrag the backend database after compacted.

---

frontend/app/index.html

SCB-491 Fix the broken links for China Region

---

etc/conf/app.conf
integration/governance_test.go
integration/instances_test.go
integration/integrationtest_suite_test.go
integration/microservices_test.go
integration/rules_test.go
integration/tags_test.go
server/bootstrap/bootstrap.go
server/plugin/pkg/uuid/context/context.go
server/plugin/pkg/uuid/uuid.go
server/service/instance.go
server/service/microservice.go

SCB-972 Using Sha1 signature key as UUID of micro service

---

server/plugin/pkg/tracing/buildin/span_test.go

SCB-993 span_test.go:151: Fatalf call has arguments but no formatting directives

---

Dockerfile.build
scripts/build/local.sh
scripts/docker/build-frontend-image/build.sh
scripts/docker/build-image/build.sh

SCB-1059 Support go 1.11.2

---

integration/health-metrics-grafana.json
pkg/etcdsync/mutex.go
pkg/notify/notice.go
pkg/notify/notification_test.go
server/core/backend/lease.go
server/notify/metrics.go
server/notify/stream.go
server/notify/websocket.go
server/plugin/pkg/discovery/etcd/cacher_kv.go
server/plugin/pkg/discovery/metrics.go
server/plugin/pkg/registry/etcd/common.go
server/plugin/pkg/registry/etcd/etcd.go
server/plugin/pkg/registry/metrics.go
server/service/event/event.go
server/service/event/schema_summary_event_handler.go
server/service/metrics/metrics.go

SCB-1092 More abundant metrics information

---

syncer/config/config.go
syncer/etcd/agent.go
syncer/grpc/server.go
syncer/serf/agent.go
syncer/serf/agent_test.go
syncer/serf/config.go
syncer/server/handler.go
syncer/server/server.go
syncer/servicecenter/servicecenter.go
syncer/servicecenter/servicecenter_test.go

Abstract control flow from serf/etcd/grpc.
---

 [SCB-1301] Abstract control flow from serf/etcd/grpc

---

go.mod

It solves the performance problem of etcd under the large database size.
See details,
https://www.cncf.io/blog/2019/05/09/performance-optimization-of-etcd-in-web-scale-data-scenario/
https://github.com/etcd-io/bbolt/pull/141
---

[SCB-1653] Use bblot version 1.3.3

---

go.mod

upgrade dependency paas-lager to v1.1.1
```shell
go get github.com/go-chassis/paas-lager@v1.1.1
go mod tidy
```

upgrade dependency paas-lager to v1.1.1

---

docs/get-started/install.md

I think maybe the annotation means that "the project prefer to golang version greater than 1.11" not "greater then 1.11"?

typo error

---

docs/user-guides/rbac.md

Hi team,
Recently I've built `service-center` from master and configured RBAC to test it. During RBAC configuring I've encountered an error `invalid pwd`. Looking at the sources I've realized that root account password must conform to a certain set of rules.
I've made appropriate changes in `rbac.md` so that other users won't spend their time trying to figure out what's wrong 😃

Describe password requirements for root account

---

server/plugin/registry/etcd/common.go
server/plugin/registry/etcd/etcd.go
server/plugin/registry/etcd/etcd_test.go

修复问题：健康检查成功时reopen了etcd client，导致旧client被close，使用旧client的请求报错：`grpc: the client connection is closing`。修改为：只有健康检查失败才reopen etcd client。
https://github.com/apache/servicecomb-service-center/blob/3a32227ecc38b431c725209a0a413524eec3992f/server/plugin/registry/etcd/etcd.go#L746-L758
---

Fix health check bug

---

server/service/microservice_test.go
server/service/ms/datasource.go
server/service/ms/etcd/etcd.go
server/service/ms/etcd/etcd_suite_test.go
server/service/ms/etcd/etcd_test.go
server/service/ms/manager_test.go
server/service/ms/options.go

Implement ms datasource register service in etcd mode.
+ datasource framework: https://github.com/apache/servicecomb-service-center/pull/695
Refactoring service-center to make it support different backend storage(Etcd, Mongo, etc.) and kv design
At this point, register-information from services in mesh could be stored in etcd cluster(embeded or isolated-cluster) with a certain kv design format(see the design example [here](https://github.com/apache/servicecomb-service-center/blob/master/examples/etcd_data_struct.yaml)).
Howere, the service-comb can not make it if new kv design format from another database want to be introduced to the project. For example, kv format will be designed like [this](https://github.com/apache/servicecomb-service-center/blob/master/examples/mongodb_data_struct.yam …

[Enhancement] implement ms datasource register service in etcd mode

---

server/service/dep/etcd/util.go
server/service/ms/etcd/etcd.go
server/service/ms/etcd/util.go

+ Keep util functions under service/util still  be used by ms/etcd/etcd.go as serviceUtil.xxx.
> Reason: functions in xxx_util.go under service/util  invoke each other, when we migrate these xxx_util.go-functions to service/ms/etcd/utils.go and service/dep/etcd/utils.go, it will lead package loop dependency error and blocked in  golang-lint check.
+ In the future, for different implementation of datasource interface, such as  mongo, util funcs can works under directory service/util/mongo
#703 -- service/ms interface implement
#701 -- service/ms interface implement
#697 -- background of the enhancement, service/ms interface implement
#695 -- framework of the enhancement

[enhancement] optimize service/util func invoker in ms/etcd package

---

datasource/etcd/ms.go
datasource/etcd/util.go
datasource/mongo/account.go
datasource/mongo/account_test.go
datasource/mongo/client/errortypes.go
datasource/mongo/client/mongo.go
datasource/mongo/database.go
datasource/mongo/ms.go
datasource/mongo/ms_test.go
datasource/schema_util.go

1.service,tag融合为单张表，尽可能减少事务操作
2.schema涉及和service的同时更新，事务无法避免
3.quota，version,service中涉及dep，instance的删除更新后续PR补齐
4.当前只保证了基础功能的ut，先不影响性能测试，后续PR补齐分支，且事务ut需要mongo集群。

SCB-2094 implement basic service/rule/schema/tag interface

---

datasource/mongo/system.go
go.mod

mongo缓存用go-cache重构实现后变更了foreach方法，因此更新DumpCache接口

Update Mongo DumpCache Interface

---

datasource/mongo/event/event.go
datasource/mongo/event/instance_event_handler.go
datasource/mongo/event/instance_event_handler_test.go

1. 实例增量数据校验，增量数据类型转换。
2. 向syncer发送同步数据。
3. 缓存中若无增量实例对应的服务数据，将访问一次数据库。
修改：
1. 删除读取配置文件的代码，采用系统自带mongo配置
2. 删除notify状态检查
3. 常量应用和代码规范

sync data processer

---

syncer/servicecenter/sync.go

实例同步时SC会先http请求查看同步实例对应的service是否存在，service不存在时http请求错误，若此时return，service将不会创建导致同步失败。

修复同步时无法生成service问题

---

datasource/mongo/sd/mongo_cacher.go

问题：
event的value会出现nil的情况，后续逻辑把event转换为service和instance的时候会panic
触发条件：
list比watch先发现某条数据被删除了
例如：
1. SC缓存中本来有数据A，这时候删除mongodb的这条数据A
2. 这时候watch连接是断开的，并且正开始执行list操作，list到的数据发现A数据已经删除了，就根据数据A的resourceId\value生成delete类型的event放入队列，并且把数据A从缓存里删除
3. 等list完，watch连接重新建立，并且根据记录的resumeToken点开始取数据，又会watch的数据A的delete操作，但是该数据已经不再缓存里了，就无法从缓存中取出数据A的值来生成event，就会出现event的value为nil的情况
根因：
1.watch mongodb delete操作的时候，只能拿到documentId，所以推送delete的event，需要从缓存中取数据
2.mongodb的list watch操作没有revision这个东西，但有resumetoken可以让watch感知到上次是从哪里开始watch的，但是list的时候拿不到resumetoken
关联issue: https://github.com/apache/servicecomb-service-center/issues/847

mongo listwatch bug fix

---

datasource/mongo/client/common.go
datasource/mongo/client/mongo.go
datasource/mongo/mongo.go
etc/conf/app.yaml
go.mod
scripts/build/local.sh

【issue】: #857
【特性/模块名称】：db为mongo支持CA证书校验
【修改内容】：db为mongo支持CA证书校验
【自测情况】：ut全部通过
【说明】
mongo的[server配置](https://docs.mongodb.com/v4.0/tutorial/configure-ssl/) 
1. client需要CA证书校验，mongo启动配置
sc的yaml配置中certFile与keyFile可以为空如下图
2. 判断client证书的有效性，mongo启动配置
sc的yaml配置全不能为空如下图
3. 若想调过证书验证（即sc的yaml配置中certFile与keyFile可以为空），mongo启动配置如下

[SCB-2094]Mongo supports CA certificate verification

---

datasource/mongo/ms.go

【issue】: #845
【特性/模块名称】：mongo支持缓存心跳模式
【修改内容】：
1. 当创建实例成功时，再去请求一次实例心跳。—— 解决问题: 当用户只创建了实例，未发送心跳，超时删除操作由mongo转向sc
【自测情况】：ut全部通过

[SCB-2094] Bugfix-cache heartbeat mode in mongo

---

syncer/plugins/servicecenter/transform.go
syncer/plugins/servicecenter/transform_test.go

【issue】: https://github.com/apache/servicecomb-service-center/issues/875
【特性/模块名称】：syncer模块传数据时的数据类型转换
【修改内容】：
1.新增transform_test
2.修复空指针异常代码
【自测情况】：ut全部通过

add ut of transform, fix bug in transform

---

datasource/mongo/ms.go

【issue】: #878
【特性/模块名称】：查询实例相关日志打印不清晰
【修改内容】：
查询实例时，需要打印相关错误日志，过滤服务以及根据明确实例id查询这两个错误日志模糊，无法区分。
【自测情况】：ut全部通过

[SCB-2094] Bugfix-the printing information of relevant logs is not clear

---

deployments/db.js
examples/dev/README.md
examples/dev/conf/app.yaml
examples/dev/docker-compose.yaml

【issue】: #887 
【特性/模块名称】：缺少对接mongo的开发指导步骤文档
【修改内容】：
模仿kie，新增examples/dev相关内容
需要完善的地方：
整合etcd使用，app.yaml做适量删除，考虑sc创建索引和db.js合一

[SCB-2094]add mongo dev doc

---

server/plugin/quota/buildin/buildin.go
server/plugin/quota/quota.go

配额管理需要支持context管理，可能有的插件实现需要判断上下文，来返回配额限制

add context

---

datasource/etcd/kv/instance_event_handler.go
datasource/etcd/sd/etcd/cacher_kv.go
pkg/metrics/common.go
server/config/util.go
server/metrics/meta.go
server/plugin/quota/buildin/buildin_test.go
server/plugin/quota/quota.go

在设计中，defer handler会在一个条件下被Reset，导致自我保护机制中残留需要被重放的实例删除event，实例删除event不被重放，那么就会涉及到很多数据一致性问题，例如当前的实例占用数量，导致配额数据不重启就永远不刷新

self preservation can not replay events

---

.gitignore
pkg/privacy/password.go
pkg/privacy/password_test.go
server/service/rbac/authr_plugin.go
version/version.go

increase token signing performance

---

datasource/mongo/ms.go

【issue】: #926
【特性/模块名称】：性能优化
【修改内容】：
创建实例成功后，没有必要去再去掉心跳，这样会降低注册实例接口调用的性能，若注册成功后未发心跳，删除工作由mongo来删除（目前300s） ，之前pr https://github.com/apache/servicecomb-service-center/pull/872
1.剔除创建实例成功后去发送心跳
【自测情况】：ut全部通过

There is no need to send heartbeat when the instance is registered successfully

---

datasource/mongo/heartbeat/cache/heartbeatcache.go
datasource/mongo/heartbeat/cache/heartbeatcache_test.go

【issue】: #942
【特性/模块名称】：cache插件命名不规范，可读性不行
【修改内容】：
1. cache插件的命名不好理解，修改为HeartBeatCache
【自测情况】：ut全部通过
【学习】
go init是根据包导入位置来定的，所以心跳插件加载时，map是不需要加锁的。感谢华哥
https://golang.org/ref/spec#Package_initialization

SCB-2094 Fix: Nonstandard naming Heartbeatcheck

---

datasource/mongo/heartbeat/cache/heartbeat.go
datasource/mongo/heartbeat/cache/heartbeat_test.go
datasource/mongo/heartbeat/cache/heartbeatcache.go
datasource/mongo/heartbeat/cache/heartbeatcache_test.go
datasource/mongo/heartbeat/cache/types.go
datasource/mongo/heartbeat/checker/heartbeatchecker.go
datasource/mongo/ms.go

【issue】: #944
【特性/模块名称】：实例及时下线
【修改内容】：
新建接口检查任务，用于创建实例成功后调用，即当db为mongo心跳插件选用cache时，注册实例成功后，加入缓存，用于检查——实现功能，注册完实例后也能及时下线
【自测情况】：ut全部通过

SCB-2094 BugFix: join the heartbeat cache

---

README.md
datasource/mongo/event/instance_event_handler.go
datasource/mongo/fast_register_config.go
datasource/mongo/fast_register_inst_service.go
datasource/mongo/fast_register_test.go
datasource/mongo/fast_register_timer.go
datasource/mongo/mongo.go
datasource/mongo/ms.go
datasource/mongo/types.go
docs/user-guides.rst
docs/user-guides/fast-registration.md
etc/conf/app.yaml

【issue】: #948 
【特性/模块名称】：实例快速注册特性
【修改内容】：
默认使用实例注册流程，添加快速注册流程，并加上开关
如果开启快速注册开关，注册实例时候直接把实例放到队列然后返回
通过定时任务进行批量注册到mongodb
【自测情况】：
ut全部通过
基本流程测试通过
性能测试数据： 
tps 9w (sc 8u16g*2  mongodb16u32g ),
tps 15w (sc 16u32g*2  mongodb16u32g )

SCB-2094 Fast register with mongo

---

datasource/account.go
datasource/account_test.go
datasource/etcd/account.go
datasource/etcd/path/key_generator.go
datasource/etcd/role.go
datasource/mongo/client/mongo.go
datasource/mongo/role.go
examples/etcd_data_struct.yaml
server/resource/v4/role_resource.go
server/resource/v4/role_resource_test.go

方案：
etcd
- 使用etcd的事务进行账号的增删，增的时候创建角色到账号的映射key path（无value），删的时候也删除映射
- 角色删除时ls 映射的key path，看看是不是存在映射，不存在才能删除
mongo
- 删除角色时，按条件查询下是不是包含在账号内的角色字段内

role binding check

---

pkg/privacy/password.go
pkg/privacy/password_test.go

10x faster than default scrypt params
reduce iteration from 16384 to 1024
reduce Salt len from 16 bytes to 8 bytes

optimize perf on token signature

---

datasource/mongo/client/mongo.go
datasource/mongo/mongo.go
etc/conf/app.yaml

【issue】: #1052
【特性/模块名称】：mongo db 连接
【修改内容】：
新增配置项registry.mongo.cluster.poolSize，把该参数设置为可以配置的，默认设置为1000
创建mongoclient的时候传入参数，扩大go driver与mongo的连接数量
【自测情况】：
测试通过，通过配置poolSize可以提高go driver 与mongo的连接数量，高并发场景酌情配置

fixbugs: mongo connection pool is full (#1052)

---

datasource/mongo/ms.go
datasource/service_test.go

【issue】: #1058
【特性/模块名称】：GetServicesInfo查询错误
【修改内容】：
GetServicesInfo函数
1. 最终返回的 statistics 为nil
2. filter过滤servicename填写错误
【自测情况】：ut全部通过

bugfix: GetServicesInfo function return wrong statistics

---

datasource/mongo/mongo.go

【issue】: #1072 
【特性/模块名称】：mongo索引修改
【修改内容】：
1. 使用tenant+服务id为唯一索引，避免两个租户用户指定同服务id冲突的问题
【自测情况】：
测试通过

change service col unique index

---

docs/user-guides/rbac.md
etc/conf/app.yaml
server/handler/auth/auth.go
server/plugin/auth/auth.go
server/plugin/auth/buildin/buildin.go
server/plugin/auth/buildin/buildin_test.go
server/plugin/auth/buildin/parser.go
server/plugin/auth/buildin/parser_test.go
server/resource/register.go
server/service/rbac/account_service.go
server/service/rbac/context.go
server/service/rbac/rbac.go
server/service/rbac/resource.go

当前enbleRBAC控制了2个特性的开关：
1. API的认证鉴权
1. Account、Role的API是否注册到路由
这就表示，必须开启认证才能进行accout和role的规划维护，这样对于生产环境开启安全认证，用户只能选择中断业务或被迫全部使用root来达到平滑切换目的，现在打算这样解决：
1. 在开启rbac时，增加一个resource scope的概念，用于指定认证鉴权的资源范围，支持*表示默认鉴权所有资源。
1. 在切换时先设置scope=account,role，保证其他资源不受影响，等维护好account和对应的role权限，并进行分发给SDK侧配置认证信息后，再更新scope=*可以达到平滑开启的效果。
1. 支持开启rbac，不传初始化root密码跳过root账号创建，支持通过private key签发root的token，调用API创建root账号

Feature: Add authentication resource scope

---

datasource/etcd/state/etcd/indexer_etcd.go
datasource/etcd/state/parser/parser.go
datasource/etcd/value/parser_test.go

场景：当KV存储的数据原类型为[]byte，string时，解析器会认为nil是非法结果，导致解析失败
解决方案：当解析器遇到nil，原类型[]byte应解析成nil，string解析成""

Bug: continue if parse value failed

---

datasource/cache/ms_cache.go
datasource/common.go
datasource/instance_test.go
datasource/mongo/client/dao/dep.go
datasource/mongo/dep.go
datasource/mongo/dep_util.go
datasource/mongo/dependency_query.go
datasource/mongo/event/instance_event_handler.go
datasource/mongo/instance_util.go
datasource/mongo/microservice_util.go
datasource/mongo/ms.go
datasource/mongo/sd/instance_cache.go
datasource/mongo/sd/instancec_test.go
datasource/mongo/sd/service_cache.go
datasource/mongo/sd/servicec_test.go
datasource/mongo/util.go

【issue】: #1066
【特性/模块名称】：缓存查询优化
【修改内容】：
1.所有查询service/instance/dep的地方都由从db查询修改为先从缓存中查询，如果缓存中没有再查db
根据version版本匹配的地方暂未修改，后续实现了缓存version匹配再修改
2.service/instance/的index由原来的{serviceID}修改为{domain}/{project}/{serviceID}的形式
否则多域下出现serviceID相同的情况查询会有问题
【自测情况】：
测试通过

Get service/instance from cache (#1066)

---

datasource/etcd/etcd.go
datasource/etcd/path/key_generator.go
datasource/role_test.go
integration/instances_test.go

问题复现：
Step 1. 创建一个角色，并绑定到一个已有帐号
Step 2. 创建一个跟上一步跟角色名称是前缀包含的新角色后
Step 3. 删除新角色会报错
根因：检查角色是否绑定帐号的etcd实现中，前缀匹配查询没有增加“/”结尾，导致前缀相同的其他角色的帐号都误认为是当前角色绑定的
修复方案：前缀匹配增加“/”
---

Fix: Can not delete unused role

---

go.mod

【issue】：#1173
【修改内容】：go mod
【修改原因】：go mod 中的 require 中 直接依赖和间接依赖存在一起
【影响范围】：无

Use go 1.17 to distinguish indirect dependencies

---

.github/workflows/eventbase-ci.yml
.github/workflows/static_check.yml
scripts/docker-compose.yaml
scripts/ut_test_in_docker.sh

【修改内容】：修改 mongo 的 ci，开启副本集
【修改原因】：之前 mongo ci 测试用例副本集没有开启，还有 apache 这边只能支持 apache 自身拥有权限的 ci action，所以这边使用docker-compose
【影响范围】：无
【额外说明】：无
【测试用例】：无

[fix] modify ci to use mongo replica set

---

datasource/dlock/dlock.go
datasource/dlock/dlock_test.go
datasource/dlock/init.go
datasource/dlock/options.go
datasource/etcd/dlock.go
datasource/manager.go
go.mod
go.sum
server/service/dlock/dlock.go
server/service/dlock/dlock_test.go

【issue】：#1192
【修改内容】：
1、新增 dlock 用于锁定 key，来进行其他操作
【修改原因】：需要有 dlock 机制
【影响范围】：无
【额外说明】：此 pr 只实现了 db 为 etcd 的情况，mongo 后面补充
【测试用例】：都增加相关接口的测试用例，自测全部通过

[feat] add dlock service, implemented etcd's dlock mechanism

---

datasource/common.go
datasource/etcd/account_test.go
datasource/etcd/role.go
datasource/etcd/role_test.go

【issue】#1196
【修改内容】：当开启同步时，创建、修改、删除 role 都会新增task，删除会新增tombstone
【修改原因】：同步功能需求
【影响范围】：无
【额外说明】：无
【测试用例】：
开启同步任务：
1、创建一个role，删除该role，会创建2个task，以及一个tombstone
2、创建两个role，更新这两个，然后删除，会创建6个task，以及2个tombstone

[feat] add role sync func and ut when db is etcd

---

datasource/common.go
datasource/etcd/dep.go
datasource/etcd/dep_test.go

【issue】#1196
【修改内容】：当开启同步时，创建和更新dep会创建同步任务
【修改原因】：同步功能需求
【影响范围】：无
【额外说明】：这边dep其实有个问题，就是之前的接口将add和update都使用了同一个接口，导致这边无法区分sync任务的状态，还有这边update还有删除的意思，其实之前的接口应该很有问题
【测试用例】：
开启同步任务：
1、创建一个consumer和一个Provider服务，consumer去订阅Provider，会创建一个同步任务

[feat] add dep sync func when db is etcd

---

datasource/etcd/dep.go
datasource/etcd/dep_test.go

【issue】#1196
【修改内容】：根据接口的 override的状态确认其dep资源task任务的状态，true 表示 create，false表示update，具体接口看[链接1](https://github.com/apache/servicecomb-service-center/blob/160431cbf8d33644cbd526e496b1a0554de0afd8/server/service/disco/dependency.go#L29) 和[链接2](https://github.com/apache/servicecomb-service-center/blob/160431cbf8d33644cbd526e496b1a0554de0afd8/server/service/disco/dependency.go#L41)
【修改原因】：修复上一个[PR](https://github.com/apache/servicecomb-service-center/pull/1200)，只有update dep task的状态，应该有两个状态，create和update
【影响范围】：无
【额外说明】：无
【测试用例】：
开启同步任务：
1、创建一个consumer和两个Provider服务，consumer先去创建订阅Provider，会创建一个create类型的同步任务
2、consumer然后再去订阅第二个Provider，会创建一个update类型的同步任务

[fix] distinguish creating and updating dep tasks

---

datasource/common.go
datasource/etcd/ms.go
datasource/etcd/ms_test.go

【issue】#1196
【修改内容】：当开启同步接口后，创建、更新、删除service都会创建相应类型的task，删除服务时还会创建相应的tombstone
【修改原因】：同步任务功能需要
【影响范围】：无
【额外说明】：无
【测试用例】：
开启同步任务：
1、创建 microservice，会创建一个create 状态以及service资源类型的 task
2、更新这个服务，会创建一个update状态以及service资源类型的 task
3、删除这个服务，会创建一个delete状态以及service资源类型的task，还有一个tombstone

[feat] add microservice sync func and ut when db mode is etcd

---

datasource/etcd/ms.go
datasource/etcd/schema.go
datasource/etcd/schema_test.go

【issue】#1196
【修改内容】：
1、当开启同步接口后，更新、删除schema都会创建相应类型的kv task，删除schema时还会创建相应的tombstone
2、修改了部分包导入import的重名，改成倒数第二个包首字母+最后包名
【修改原因】：
1、sync同步功能事务落盘
【影响范围】：无
【额外说明】：无
【测试用例】：
开启同步任务：
1、创建一个服务，会创建一个 service类型状态为create的task
2、更新schema，会创建  3 个类型为kv状态为update的tasks
3、更新schemas，会创建7 个类型为kv状态为update的task，2个类型为 kv 状态为delete的task，2个kv类型的tombstone

[feat] add schema sync func and ut when db mode is etcd

---

datasource/etcd/dep_test.go
datasource/etcd/ms_test.go

【issue】#1196
【修改内容】：
1、dep用例将创建的 task 任务和tombstone都删除，以免给后面用例带来影响
2、ms用例中将context.Background()修改成microServiceGetContext()指定的上下文
【修改原因】：
1、sync同步功能事务落盘
【影响范围】：无
【额外说明】：无
【测试用例】：做修复，见修改内容

[fix] fix test cases for services and dependencies when the db mode is etcd

---

etc/conf/app.yaml
server/core/microservice.go

【issue】#1207
【修改内容】：config增加datacenter 信息，获取实例的时候读取配置信息 
【修改原因】：获取实例接口增加datacenter 信息
【影响范围】：无
【额外说明】：无
【测试用例】：无

[feat] add datacenter info to instance from config

---

datasource/etcd/account.go
datasource/etcd/account_test.go
datasource/etcd/dep_test.go
datasource/etcd/ms.go
datasource/etcd/ms_test.go
datasource/etcd/role_test.go
datasource/etcd/schema.go
datasource/etcd/schema_test.go
datasource/etcd/sync/sync.go
datasource/etcd/sync/sync_test.go
datasource/etcd/tag_test.go
pkg/util/common.go
pkg/util/context.go
server/handler/context/context.go

【issue】#1196
【修改内容】：
1、修改拦截器，若sc开启同步开关，则正常流量访问需要落盘同步，同步请求访问service不需要进行落盘
【修改原因】：
1、sync同步功能事务落盘
【影响范围】：无
【额外说明】：开启同步开关，正常业务流量访问需要落盘，同步请求不需要进行落盘
【测试用例】：
1、测试用例做了部分修改，主要还是在ctx里传入了开启同步的配置

[feat] normal access traffic needs to be synchronized

---

etc/conf/app.yaml
server/config/util.go
server/config/util_test.go
server/service/disco/instance.go
server/service/disco/instance_test.go
test/test.go

【issue】#1219
【修改内容】：配置中增加实例的引擎信息，注册实例的时候加上配置的引擎信息
【修改原因】：增加引擎信息到实例中去
【影响范围】：无
【额外说明】：无
【测试用例】：无

[feat] add engine info to instance

---

eventbase/README.md
eventbase/bootstrap/bootstrap.go
eventbase/datasource/manager.go
eventbase/datasource/manager_test.go
eventbase/service/task/task_svc_test.go
eventbase/service/tombstone/tombstone_svc_test.go
eventbase/test/test.go
syncer/service/tombstone/tombstone_test.go
test/test.go

【issue】#1227
【修改内容】：
1.使用 cari 连接db的 clint，[cari修改地址](https://github.com/go-chassis/cari/pull/52)
2.event需要传入kind的db类型，前提需要保证db已经初始化好了
【修改原因】：
1、减少db的client创建
【影响范围】：无
【额外说明】：无
【测试用例】：无

[feat] eventbase use db kind

---

datasource/etcd/etcd.go
datasource/etcd/ms.go
datasource/mongo/mongo.go
datasource/mongo/ms.go
datasource/ms_util.go
datasource/ms_util_test.go
datasource/options.go
server/server.go

背景：管控面接口-返回所有微服务实例信息，由于考虑返回body体大小的原因，将properties属性禁止输出了；此优化与内置实例属性的需求矛盾，需求要求返回properties内置的属性。
修改方案：如存在内置属性，仅输出内置属性，自定义属性依然在微服务详情接口中返回
---

Bug: return internal properties when list all microservices

---

datasource/mongo/account.go
datasource/mongo/account_test.go
datasource/mongo/db.go
datasource/mongo/dep.go
datasource/mongo/dep_test.go
datasource/mongo/model/types.go
datasource/mongo/ms.go
datasource/mongo/ms_test.go
datasource/mongo/role.go
datasource/mongo/role_test.go
datasource/mongo/sync/sync.go
eventbase/go.mod
eventbase/go.sum
go.mod
go.sum

【issue】#1196
【修改内容】：
1、account事务落盘
2、dep事务落盘
3、role事务落盘
4、ms事务落盘
5、心跳实例发送到event
【修改原因】：
1、sync同步功能
【影响范围】：无
【额外说明】：
1、tag还未落盘
2、schema 对于mongo来说不需要
【测试用例】：
1、复用 etcd 之前写的事务落盘，保障整体功能的可靠性

[feat] add task tombstone when db is mongo

---

datasource/etcd/etcd.go
datasource/etcd/path/key_generator_test.go
datasource/etcd/sync.go
datasource/etcd/sync_test.go
datasource/manager.go
datasource/mongo/mongo.go
datasource/mongo/sync.go
datasource/sync.go

【issue】#1196
【修改内容】：
1、增加 syncAll 的 func
【修改原因】：
1、sc一开始没enableOnStart，且sc里面已经有数据了，后面我改配置enableOnStart为true，这些已有数据就没法同步了，需要提升可靠性
【影响范围】：无
【额外说明】：
需要sc启动时候：
1、判断enableStart是否true
2、如果true，查询sync-all key是否存在
3、如果不存在，执行sync all逻辑
4、sync all完成后，写sync-all key
【测试用例】：
1、enableOnStart开关未开启，不会做同步功能
2、enableOnStart开关开启，但是已经有SyncAllKey字段表示已经同步过，不需要再做同步了
3、enableOnstart开关开启，而且SyncAllKey字段不存在，需要做同步
- 创建三个service，并且删除其创建过程的task
- 创建一个account，并且删除其创建过程的task
- 创建一个role，并且删除其创建过程的task
- 创建一个schema，并且删除其创建过程的task
- 创建一个tag，并且删除其创建过程的task
- 创建一个dep，并且删除其创建过程的task
**执行SyncAll的操作，会创建4个kv（3个schema，1个tag），3个service，1个account，1个role，1个dep**
删除所有资源

[feat] add SyncAll func

---

datasource/etcd/sync.go
datasource/etcd/sync_test.go

【issue】#1196
【修改内容】：
1、在syncAll的func中添加锁 SyncAllLockKey 的锁
【修改原因】：
1、防止多个 sc 进行重复操作
【影响范围】：无
【额外说明】：无
【测试用例】：
1、先获取SyncAllLockKey的锁，然后执行同步任务，实际不会进行同步

[fix] add SyncAllLockKey in SyncAll func

---

datasource/mongo/db.go
datasource/mongo/model/types.go
datasource/mongo/sync.go
datasource/mongo/sync_test.go

【issue】#1196
【修改内容】：
1、增加 syncAll 的 func
【修改原因】：
1、sc一开始没enableOnStart，且sc里面已经有数据了，后面我改配置enableOnStart为true，这些已有数据就没法同步了，需要提升可靠性
【影响范围】：无
【额外说明】：
需要sc启动时候：
1、判断enableStart是否true
2、如果true，查询sync-all key是否存在
3、如果不存在，执行sync all逻辑
4、sync all完成后，写sync-all key
【测试用例】：
1、enableOnStart开关未开启，不会做同步功能
2、enableOnStart开关开启，但是已经有SyncAllKey字段表示已经同步过，不需要再做同步了
3、enableOnstart开关开启，而且SyncAllKey字段不存在，需要做同步
创建两个个service，并且删除其创建过程的task
创建一个account，并且删除其创建过程的task
创建一个role，并且删除其创建过程的task
创建一个dep，并且删除其创建过程的task
执行SyncAll的操作，会创建，2个service，1个account，1个role，1个dep
删除所有资源

[feat] add SyncAll func when db is mongo

---

etc/conf/app.yaml
server/service/disco/instance.go
server/service/disco/instance_test.go

Feature: append inner properties when heartbeat success

---

datasource/etcd/ms.go
datasource/etcd/schema.go
datasource/etcd/schema_test.go
datasource/etcd/sync_test.go
datasource/etcd/util.go
datasource/etcd/util/dependency_util.go
datasource/etcd/util/microservice_util.go
server/service/rbac/rbac.go

【issue】https://github.com/apache/servicecomb-service-center/issues/1196
【修改内容】：
1、通过排除 generate key 发现还是一部分 task 任务未同步，主要是 schema，service 更新，服务依赖dep-queue，已经初始化时 rbac 的 root 账号
【修改原因】： 
1、bug 修复，依赖关系同步后未发现服务之前的同步关系
2、初始化 root 未同步
【影响范围】：无
【额外说明】：无
【测试用例】：
1、由于修改了DeleteContent会多创建一个kv类型的task，schema-content，所以在schema测试用例和sync测试用例中，查询时从原先的3改成了4

[bugfix] AddServiceVersionRule func should add sync task when sync is enabled

---

datasource/etcd/sync.go
server/service/rbac/rbac.go

【issue】https://github.com/apache/servicecomb-service-center/issues/1196
【修改内容】：
1、修改account和role同步顺序
【修改原因】：
1、修改account和role同步顺序
【影响范围】：无
【额外说明】：无
【测试用例】：
无

[fix] exchange account and role order in SynAll func

---

datasource/etcd/sync.go
datasource/etcd/sync_test.go
datasource/mongo/sync.go
datasource/mongo/sync_test.go

【issue】https://github.com/apache/servicecomb-service-center/issues/1196
【修改内容】：
1、调用SyncAll的func时需要设置下 context的sync开关
【修改原因】：
1、开启RBAC单引擎可靠性升级到双引擎，升级创建出来的引擎使用rbac帐号、密码登录失败 
【影响范围】：无
【额外说明】：无
【测试用例】：
1、添加了一个测试用例，使用 context.Background() 调用 SyncAll 这个 func

[bugfix] set sync context when call SyncAll func

---

README.md

ServiceCenter now needs go 1.17 to build

[DOC] [MINOR]ServiceCenter now needs go 1.17 to build

---

docs/release/Readme.md
docs/release/releaseNotes-2.1.0.md

【修改内容】：新增 sc 的 2.1.0 版本的releaseNotes
【修改原因】：发布2.1.0版本
【影响范围】：无
【额外说明】：无
【测试用例】：无需修改测试用例

[feat] add sc 2.1.0 releaseNotes

---

datasource/etcd/ms.go
datasource/mongo/ms.go
server/service/disco/metadata.go

【修改内容】
1、将service的时间修改移动到resource层
【修改原因】
1、在同步中发先，同步过去的service会重新修改这个时间。当两个引擎正在通过，连续触发创建服务和删除服务的时候，会导致删除服务事件被抛弃，因为另外一个引擎在创建服务时会把之前原先的时间给修改了，导致事件呗抛弃
【测试用例】无需修改测试用例

[bug] move the time setting of the service to the disco layer

---

.github/workflows/eventbase-ci.yml
.github/workflows/static_check.yml
frontend/app/scripts/modules/serviceCenter/controllers/schemaCtrl.js
frontend/app/scripts/modules/serviceCenter/controllers/serviceInfoCtrl.js
frontend/app/scripts/scRouterConfig.js

【问题】前端页面当点击详细服务时，改服务的schema没办法展示，因为新版本list接口返回的微服务是没有schema信息的，所以要换成用service详情接口来查
【修改内容】修改相关的 js，接口调用方式由原先的查询所以，改成查询指定 id 的service
【测试用例】无需修改

[fix] modify schema url in frontend

---

syncer/service/admin/health.go

【修改内容】增加 syncer 中的 health 初始化时对enableOnStart字段判断
【修改原因】若未开启同步，health连接clint会不断尝试grpc连接打印相关日志
【测试用例】无需修改

[fix] add enableOnStart conditional judgment in syncer health init

---

frontend/app/scripts/modules/dashboard/views/dashboard.html

【修改文件】前端页面一些链接
【修改原因】链接失效了
【测试用例】无需修改

[fix] userGuide.title link

---

frontend/app/apiList/apiList.js
frontend/app/scripts/modules/serviceCenter/controllers/serviceInfoCtrl.js

【背景】前端页面展示的元数据信息只包含了服务的信息，LocalCSE这边展示的数据包含所有实例以及schemas
【修改内容】
新增接口`v4/default/govern/microservices/{{serviceId}}?options=instances`
【验证】

[fix] Replace metadata URL to show more information

---

datasource/mongo/ms_test.go
examples/service_center/request/register_intance_json.sh
go.sum
server/bootstrap/bootstrap.go
server/ext/policy/buitin.go
server/resource/gov/gov_resource.go
server/resource/gov/gov_resource_test.go
server/server.go
server/service/grc/config_distributor.go
server/service/grc/config_distributor_test.go
server/service/grc/kie/kie_distributor.go
server/service/grc/mock/mock.go
server/service/grc/policy.go
server/service/grc/policy_test.go
server/service/grc/validate.go

**动机：**
- 扩展新的策略开始变得丑陋，对开发者不友好 https://github.com/apache/servicecomb-service-center/pull/1319 https://github.com/apache/servicecomb-service-center/pull/1318
- 如此扩展对构建一个生态没有帮助
**方案：**
之前已经提供了全新的validate机制，但是还没有跟整套方案无缝衔接https://github.com/apache/servicecomb-service-center/pull/1097
本次重构将新老validate机制合一并保持向前兼容

refactor policy validator

---

etc/conf/app.yaml
server/plugin/auth/buildin/buildin.go

背景：当前如果在开启身份认证的情况下，可以支持通过scope来控制资源的鉴权范围。但当前的实现把身份认证的阶段也同时跳过了。即传递一个无效的Authorization也会跳过认证阶段，可返回请求的资源。存在API的歧义，应该修改成允许不传Authorization头，但如果传，必须校验其合法性。
---

Change: always authenticate the request with HTTP Header 'Authorization'

---

server/plugin/auth/buildin/parser_test.go
server/plugin/auth/buildin/service_parser.go
server/plugin/auth/buildin/service_parser_test.go

当前服务发现接口支持：消费方调用接口是如不传query参数env时，按x-consumerId对应服务的environment来发现服务提供方；在RBAC场景下，鉴权器没有考虑这个场景，导致鉴权按query传参env的值判断，不符合预期。
---

bugfix: return 'no permission' when discover provider in specify env

---

datasource/etcd/ms.go

[fix] envindexkey should add envid when the env be deleted

---

etc/conf/app.conf
server/config/config.go
server/config/server.go
server/plugin/auth/buildin/buildin.go
server/service/rbac/rbac.go

fix some rbac problems

---

server/plugin/auth/buildin/buildin.go

[fix] fix the problem of can not require the api of kie when open rbac

---

.github/workflows/eventbase-ci.yml
.github/workflows/static_check.yml
docker-compose.yml
etc/conf/syncer.yaml
scripts/integration_test.sh
scripts/ut_test_in_docker.sh
syncer/config/config.go
syncer/rpc/auth.go
syncer/rpc/auth_test.go
syncer/rpc/server.go
syncer/rpc/server_test.go
syncer/server/server.go
syncer/service/admin/health.go
syncer/service/replicator/replicator.go

Syncer supports to enable rbac, to  improve security.

Syncer supports to enable rbac
