.travis.yml, README.md, lager/core/chug/chug.go, lager/core/ginkgoreporter/ginkgo_reporter.go, lager/core/lagertest/test_sink.go, lager/examples/main.go
Travis Configuration for CI Pipeline
=> [Issue 3] [JAV-14] Travis configuration for CI

.travis.yml, scripts/prepare_env_ut.sh
Updated the UT configuration for Server package
=> JAV-14 Updated UT Configuration for server package

.travis.yml, README.md, etc/conf/app.conf
add more build and running detail.
modify the etcd port .
=> update the readme

tests/integrationtest/apis.go, tests/integrationtest/governance_test.go, tests/integrationtest/health_test.go, tests/integrationtest/instances_test.go, tests/integrationtest/integrationtest_suite_test.go, tests/integrationtest/microservices_test.go, tests/integrationtest/rules_test.go, tests/integrationtest/tags_test.go, tests/scripts/integration_test.sh, vendor/manifest
Integration test for all API's of Service Center
=> Scaffolding for integration test

.travis.yml, tests/scripts/integration_test.sh
Seperate jobs for Build, UT and IT in CI
=> Configuration for multiple jobs in travis CI

integration/governance_test.go, integration/health_test.go, integration/instances_test.go, integration/microservices_test.go
Benchmark test cases for basic api's
=> Basic benchmark test

etc/conf/app.conf, server/core/common.go, server/core/key_generator.go, server/core/registry/embededetcd/embed_etcd_plugin.go, server/core/registry/etcd/remote_etcd_plugin.go, server/core/registry/registry.go, server/core/registry/store/cacher.go, server/core/registry/store/defer.go, server/core/registry/store/event.go, server/core/registry/store/listwatch.go, server/core/registry/store/opt.go, server/core/registry/store/store.go, server/server.go, server/service/dependency/dependency_service.go
1. Panic: etcdsync.(*Locker).Lock.
1. Regular expression error.
1. Do not refresh dependence cache in query.
1. Support self preservation.
1. Update the max header size to 32KB.
1. Remove unused key 'epsindex'.
=> New features and bug fixes.

frontend/app/scripts/modules/serviceCenter/controllers/servicesListCtrl.js
Service List default sort order based on service name.
=> Service List sort order correction

server/core/swagger/v3.yaml
(cherry picked from commit edce963)
=> Bug fix: Modify v3.yaml file

server/api.go, server/rest/controller/v3/dependency_controller.go, server/rest/controller/v4/dependency_controller.go, server/rest/controller/v4/instance_controller.go, server/rest/controller/v4/microservice_controller.go, server/rest/controller/v4/query_rule_controller.go, server/rest/controller/v4/schema_controller.go, server/rest/controller/v4/tag_controller.go, server/service/governservice_test.go, server/service/instances.go, server/service/instances_test.go, server/service/microservices.go, server/service/microservices_test.go, server/service/rule_test.go, server/service/schema_test.go, server/service/service_dependency_test.go, server/service/tag_test.go
(cherry picked from commit 9635717)
=> Bug fix: Find api can build the dependency even if the consumer has no permission.

server/core/swagger/v3.yaml, server/core/swagger/v4.yaml
(cherry picked from commit c84b8a0)
=> 新增framework registerby 的swagger信息

server/govern/service.go
(cherry picked from commit 26cf048)
=> service count calculation rule: no version for one service

server/service/schema.go
(cherry picked from commit dc43bc3)
=> schema: log optimization

server/rest/controller/v4/schema_controller.go, server/service/schema.go
(cherry picked from commit e7ab2b3)
=> 修改查询schema接口中存在的冗余日子

server/core/swagger/v3.yaml, server/plugin/infra/quota/buildin/buildin.go
(cherry picked from commit 747b848)
=> quota buildin mode,just limit all service or instance count

integration/health-metrics-grafana.json, server/core/backend/store/cacher.go, server/core/backend/store/indexer.go, server/service/util/dependency.go
(cherry picked from commit 11aaf6c)
=> Optimize log print.

server/service/service_dependency.go
=> SCB-127 Optimize log print.

server/service/instances_test.go
(cherry picked from commit 8df3835)
---
=> SCB-127 Add shared service UT.

server/core/microservice.go, server/service/instances_test.go
=> SCB-127 Bug fix: Can not find any instance of default app if SC startup in non-auth mode.

pkg/rest/client.go
=> SCB-161 Optimize restful client.

server/core/key_generator.go, server/service/instances.go, server/service/util/microservice_util.go
=> SCB-181 Unused instance index key is stored in backend.

server/error/error.go, server/infra/registry/registry.go, server/service/util/instance_util.go
(cherry picked from commit 894c251)
---
=> SCB-182 Registry client option 'WithStrKey' will set the wrong key as using non-copy string function.

pkg/util/log.go, server/core/backend/store/cacher.go, server/core/backend/store/defer.go, server/core/backend/store/indexer.go, server/govern/service.go, server/service/notification/listwatcher.go, server/service/notification/notification_healthchecker.go, server/service/notification/notification_service.go, server/service/notification/struct.go, server/service/util/instance_util.go
=> SCB-159 Watcher will get a wrong event sequence when SC modify resource concurrently.

pkg/etcdsync/mutex.go, server/rest/metric.go
=> SCB-155 Optimize metric.go

server/core/key_generator.go, server/core/microservice.go, server/service/event/dependency_event_handler.go, server/service/instances.go, server/service/service_dependency.go, server/service/service_dependency_test.go, server/service/util/dependency.go, server/service/util/microservice_util.go, server/service/util/util_suite_test.go
=> SCB-160 Support empty environment scene

etc/conf/app.conf, server/core/proto/services.go, server/error/error.go, server/infra/quota/quota.go, server/plugin/infra/quota/buildin/buildin.go, server/plugin/infra/quota/unlimit/unlimit.go, server/service/instances.go, server/service/microservices.go, server/service/rule.go, server/service/schema.go, server/service/tag.go
(cherry picked from commit ba500ee3ebf0b33a599cc200549ee530d6302597)
---
=> SCB-235 Optimize quota check log

docs/README.md, docs/sc-cluster.md
=> SCB-225 Deployment guide for running SC in cluster mode

pkg/logrotate/logrotate.go
=> SCB-255 logrotate bug fix ,non write permission, skip

server/core/common.go, server/core/proto/services.go, server/service/microservices_test.go, server/service/util/microservice_util.go, server/service/util/util_suite_test.go
=> SCB-259 Can not discovery default APP services in Shared service mode

NOTICE
Add NOTICE file and include third party dependencies which are not under
Apache 2.0 license.
---
=> [SCB-260] Add NOTICE file

scripts/docker/build-frontend-image/README.md
* Update README for the frontend
---
=> CB-90 Failed to deploy frontend Service center on Huawei Cloud

server/service/event/dependency_event_handler.go, server/service/microservices.go, server/service/util/dependency.go, server/service/util/dependency_test.go
(cherry picked from commit 9ee70e0)
---
=> SCB-269 dependency use domain-project-env level lock

server/plugin/README.md
=> SCB-295 Add plug-in mechanism doc

server/core/swagger/v3.yaml, server/core/swagger/v4.yaml
(cherry picked from commit 2168663)
---
=> SCB-309 Update the API doc

etc/conf/app.conf, integration/instances_test.go, pkg/chain/chain.go, pkg/httplimiter/httpratelimiter.go, pkg/logrotate/logrotate.go, pkg/ratelimiter/ratelimiter.go, pkg/rest/client.go, pkg/rest/route.go, server/core/backend/store/cacher.go, server/core/backend/store/defer.go, server/core/backend/store/defer_test.go, server/core/backend/store/indexer.go, server/core/backend/store/listwatch.go, server/core/backend/store/opt.go, server/core/backend/store/store.go, server/infra/quota/quota.go, server/plugin/infra/registry/etcd/etcd.go, server/rest/controller/v4/microservice_controller.go, server/service/event/dependency_event_handler.go, server/service/instances.go, server/service/instances_test.go, server/service/microservices.go, server/service/rule.go, server/service/util/dependency.go
=> SCB-296 Self preservation will never stop when SC do list-watch loop

pkg/tree/tree.go, pkg/tree/tree_test.go, server/infra/registry/registry.go, server/service/event/dependency_event_handler.go, server/service/microservices.go, server/service/service_dependency.go, server/service/service_dependency_test.go, server/service/util/dependency.go, server/service/util/dependency_test.go
=> SCB-269 remove lock for dependency handle

server/govern/service.go
=> SCB-298 v4/default/govern/microservices return self microservice information

scripts/release/README.md, scripts/release/make_release.sh
=> SCB-317 Add release scripts for service-center

scripts/release/README.md, scripts/release/make_frontend_release.sh
=> SCB-317 Add release scripts for frontend

NOTICE
Some libraries have their own notice and is not listed in our NOTICE
file. And add libraries with apache license to NOTICE.
---
=> [SCB-260] Update NOTICE

NOTICE, integration/apis.go, integration/governance_test.go, integration/schema_test.go, pkg/util/tree.go, pkg/util/tree_test.go, pkg/util/uuid.go, scripts/create_gvt_manifest(exp).sh, server/plugin/infra/uuid/buildin/buildin.go, server/service/event/dependency_event_handler.go, server/service/rule.go, server/service/service_dependency.go
=>  SCB-317 Prepare the release for Service-Center-1.0.0-m1

server/interceptor/cors/cors.go
=> SCB-328 CORS interceptor does not allow header ‘ACCEPT’

frontend/main.go
=> SCB-329 Set the default listening port in frontend

pkg/util/net.go, server/infra/registry/registry.go, server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/registry/etcd/tracing.go, server/plugin/infra/tracing/buildin/buildin.go, server/plugin/infra/tracing/buildin/span.go
(cherry picked from commit 3f48ccb)
---
=> SCB-332 Wrong json output format in zipkin file collector

NOTICE, scripts/create_gvt_manifest(exp).sh, server/interceptor/cors/cors.go, vendor/manifest
=> SCB-317 Prepare the release for Service-Center-1.0.0-m1

NOTICE, frontend/app/index.html
=> Prepare Service-Center 1.0.0-m1 Release

README.md, frontend/Readme.md, scripts/release/make_frontend_release.sh, scripts/release/make_release.sh
=> SCB-317 Update the Readme docs

server/core/backend/store/defer.go, server/govern/service.go
=> SCB-339 Exclude the version in online services calculation

pkg/rest/client.go, server/service/instances.go, server/service/tag_test.go, server/service/util/rule_util.go
2.optimize find api
(cherry picked from commit 0e5cd8e)
---
=> SCB-336 1.add ut about find instance with tag 2.optimize find api

server/core/key_generator.go, server/govern/service.go, server/plugin/infra/registry/etcd/etcd.go, server/service/microservices.go
=> SCB-339 The wrong statistics in micro-service

server/service/instances_test.go, server/service/service_dependency_test.go
=> SCB-362 Fix UT failure

docs/README.md, docs/dev-guide.md, server/infra/registry/registry.go
=> Add development guide

scripts/create_gvt_manifest(exp).sh, vendor/manifest
=> Remove unused 3rd lib github.com/olekukonko/tablewriter

scripts/release/make_release.sh, scripts/release/start_scripts/linux/start-frontend.sh, scripts/release/start_scripts/linux/start-service-center.sh, scripts/release/start_scripts/linux/stop-frontend.sh, scripts/release/start_scripts/linux/stop-service-center.sh, scripts/release/start_scripts/windows/start-frontend.bat, scripts/release/start_scripts/windows/start-service-center.bat
* Changed the kit name to apache-servicecomb-incubating-service-center-xxx 
* Reduced the binary name to service-center and frontend.
=> SCB-380 Added incubating to the release kit name

scripts/release/start_scripts/linux/stop-service-center.sh
=> SCB-392 The stop script print error message

scripts/release/NOTICE, scripts/release/licenses/NOTICE-lager, scripts/release/licenses/NOTICE-prometheus, scripts/release/licenses/NOTICE-yamlv2
=> [SCB-367] Add third party notices

pkg/validate/validate.go, server/govern/service.go, server/service/microservices.go, server/service/microservices_test.go, server/service/util/rule_util.go
=>  [SCB-376] Optimize validate parameter log print

server/plugin/infra/tracing/buildin/file_collector.go
=> SCB-389 SC does not re-create the tracing file.

pkg/validate/validate.go, server/core/backend/store/lease.go, server/core/common.go, server/core/key_generator.go, server/core/microservice.go, server/core/swagger/v3.yaml, server/core/swagger/v4.yaml, server/service/instances.go, server/service/instances_test.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go
=> SCB-411 SC can not check the reduplicate endpoints when register with ID

Dockerfile
Signed-off-by: asifdxtreme <mohammad.asif.siddiqui1@huawei.com>
---
=> Add Dockerfile to base directory

server/plugin/infra/tracing/buildin/file_collector.go, server/plugin/infra/tracing/buildin/file_collector_test.go
=> SCB-421 Tracing file collector has memory leak problem

pkg/validate/validate.go
=> [SCB-376] Optimize validate parameter log print

etc/conf/app.conf, pkg/tlsutil/tlsutil.go, pkg/tlsutil/tlsutil_test.go, server/tls/tls.go
=> SCB-432 Support using default tls cipher suites implements

server/infra/tracing/tracing.go, server/plugin/infra/registry/etcd/tracing.go, server/plugin/infra/tracing/buildin/buildin.go, server/plugin/infra/tracing/buildin/file_collector.go
=> SCB-430 Wrong parentId in tracing data

scripts/release/Dockerfile
=> SCB-469 Create a new docker file for the release

pkg/util/logrotate.go
=> SCB-510 Expire backup log files are not removed

server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/registry/etcd/etcd_test.go
=> SCB-513 Add range delete support in registry command

README.md, frontend/Readme.md, frontend/app/apiList/apiList.js, frontend/app/scripts/services/httpService.js, frontend/main.go, frontend/schema/schemahandler.go, frontend/server.go, frontend/server_test.go, scripts/release/LICENSE, scripts/release/licenses/LICENSE-echo, scripts/release/licenses/LICENSE-fasttemplate, scripts/release/licenses/LICENSE-go-colorable, scripts/release/licenses/LICENSE-go-isatty, scripts/release/licenses/LICENSE-gommon, scripts/release/licenses/LICENSE-jwt-go, vendor/manifest
Add a proxy in the frontend server, and make the httpService js to access the service-center through the proxy. 
---
=> [SCB-479] Add proxy to service-center in frontend

.gitignore, etc/conf/app.conf, integration/health-metrics-grafana.json, integration/health_test.go, pkg/async/async.go, pkg/async/async_task.go, pkg/async/async_task_test.go, pkg/chain/handler.go, pkg/util/reflect.go, pkg/util/reflect_test.go, pkg/validate/validate.go, server/core/backend/store/cache_kv.go, server/core/backend/store/common.go, server/core/backend/store/defer_instance.go, server/core/backend/store/indexer.go, server/core/backend/store/lease.go, server/core/backend/store/metric.go, server/core/backend/store/store.go, server/core/info.go, server/core/proto/services.go, server/govern/service.go, server/handler/cache/cache.go, server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/registry/etcd/logger.go, server/rest/pprof.go, server/rest/server_mux.go, server/service/event/rule_event_handler.go, server/service/event/tag_event_handler.go
=> SCB-508 Cache does not match the etcd store

server/service/instances.go
=> SCB-549 Do not check the instance endpoint whether belong to other service

server/core/backend/store/defer_instance.go
=> SCB-559 Instances count that show in Service Center frontend is incorrect

etc/conf/app.conf, frontend/main.go, pkg/util/net.go, pkg/util/net_test.go, server/api.go, server/core/backend/store/common.go, server/core/backend/store/extend.go, server/core/common.go, server/rest/server.go, server/rpc/server.go, server/server.go, server/service/schema_test.go
=> SCB-561 Support ipv6

integration/health-metrics-grafana.json, server/core/backend/store/metric.go
=> SCB-563 Fix the incorrect metric label value

frontend/app/scripts/modules/serviceCenter/controllers/serviceInfoCtrl.js, frontend/app/scripts/modules/serviceCenter/controllers/servicesListCtrl.js
---
Fix https://github.com/apache/incubator-servicecomb-service-center/issues/324
=> SCB-564 Fix Capitalization of the ServiceName in the Service list

server/service/instances.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go
=> SCB-565 Register instance with the same id will create redundant endpoint index data

server/error/error.go, server/error/error_test.go
=> SCB-572 Can not convert error to status code

frontend/app/index.html, frontend/app/scripts/languages/locale-cz.js, frontend/app/scripts/languages/locale-en.js, frontend/app/scripts/modules/serviceCenter/controllers/schemaCtrl.js, frontend/app/scripts/modules/serviceCenter/controllers/serviceInfoCtrl.js, frontend/app/scripts/modules/serviceCenter/views/schema.html, frontend/app/scripts/modules/serviceCenter/views/serviceInfo.html, frontend/app/scripts/modules/serviceCenter/views/testSchema.html, frontend/app/styles/main.css, frontend/schema/schemahandler.go, frontend/server.go
=> SCB-491 Add the Test Schema Feature

.gitignore, scripts/release/make_release.sh, server/error/error.go, server/error/error_test.go, server/service/instances.go, server/service/instances_test.go, server/service/service_suite_test.go, server/service/util/dependency.go, server/service/util/rule_util.go, server/service/watch.go, server/service/watch_test.go
=>  SCB-586 Query providers api will return null when provider is removed 

server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/registry/etcd/etcd_test.go, server/plugin/infra/registry/etcd/tracing.go
=> SCB-620 Add registry server HC machanism

server/rest/controller/v4/microservice_controller.go
=> SCB-622 Compatible with old version

README.md
=> [SCB-475] Add section for dowloading latest release in README

server/plugin/infra/registry/etcd/etcd.go
=> SCB-620 Switch to new client gracefully

frontend/app/apiList/apiList.js
=> SCB-618 Delete the microservice forcefully

DockerGuide.md, Dockerfile
=> SCB-634 Fix Docker file for m2 release

server/govern/service.go
=> SCB-678 Optimize govern api

server/service/dependency.go, server/service/event/instance_event_handler.go, server/service/event/rule_event_handler.go, server/service/event/tag_event_handler.go, server/service/instance.go, server/service/notification/common.go, server/service/notification/listwatcher.go, server/service/notification/notice.go, server/service/notification/stream.go, server/service/notification/subscriber.go, server/service/notification/websocket.go, server/service/util/common.go, server/service/util/find_cache.go, server/service/util/find_cache_test.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go, server/service/watch.go
=> SCB-680 Optimize find instance api

server/core/proto/services.go, server/service/microservice_test.go, server/service/microservice_validator.go
=> SCB-694 Add 'PLATFORM' register type

frontend/app/scripts/modules/serviceCenter/controllers/schemaCtrl.js
=> SCB-695 Fix lengthy value error in testSchema

server/handler/cache/cache.go, server/rest/controller/v4/instance_controller.go, server/service/instance.go, server/service/instance_test.go, server/service/util/find_cache.go, server/service/util/find_cache_test.go, server/service/util/instance_util.go
=> SCB-680 Fix the wrong rev in find instance api

server/core/backend/cache_kv.go, server/plugin/infra/registry/etcd/etcd.go, server/service/util/dependency.go, server/service/util/microservice_util.go
=> SCB-707 Etcd connection leak, lose events and cache mismatch in SC

.gitignore, etc/conf/app.conf, pkg/rest/client.go, pkg/tlsutil/common.go, pkg/tlsutil/config.go, pkg/tlsutil/tlsutil.go, server/bootstrap/bootstrap.go, server/infra/tls/tls.go, server/plugin/README.md, server/plugin/infra/registry/embededetcd/embededetcd.go, server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/tls/buildin/buildin.go, server/plugin/infra/tls/buildin/tls.go, server/plugin/infra/tls/buildin/tls_test.go, server/plugin/plugin.go, server/rest/server.go, server/rpc/server.go
=> SCB-714 Support TLS plugin

scripts/release/README.md, scripts/release/make_release.sh
https://github.com/apache/incubator-servicecomb-service-center/issues/329 Follow this checklist to help us incorporate your contribution quickly and easily:
---
=> SCB-724 Add scripts for Mac OS release

scripts/release/make_release.sh, scripts/release/start_scripts/mac/start-frontend.sh, scripts/release/start_scripts/mac/start-service-center.sh, scripts/release/start_scripts/mac/stop-frontend.sh, scripts/release/start_scripts/mac/stop-service-center.sh
=> Update Mac Binaries script

frontend/app/scripts/modules/dashboard/views/dashboard.html, scripts/release/LICENSE, scripts/release/licenses/LICENSE-ccache
=> Fix 1.0.0 Release issues

scripts/release/LICENSE, scripts/release/LICENSE-siddontang, scripts/release/licenses/LICENSE-couchbase, scripts/release/licenses/LICENSE-ginkgo, scripts/release/licenses/LICENSE-go-humanize, scripts/release/licenses/LICENSE-go-runewidth, scripts/release/licenses/LICENSE-go-toml, scripts/release/licenses/LICENSE-goes, scripts/release/licenses/LICENSE-goleveldb, scripts/release/licenses/LICENSE-golz4, scripts/release/licenses/LICENSE-gomega, scripts/release/licenses/LICENSE-gomemcached, scripts/release/licenses/LICENSE-govaluate, scripts/release/licenses/LICENSE-kr-logfmt, scripts/release/licenses/LICENSE-kr-pty, scripts/release/licenses/LICENSE-ledisdb, scripts/release/licenses/LICENSE-lib-pq, scripts/release/licenses/LICENSE-mmap-go, scripts/release/licenses/LICENSE-pflag, scripts/release/licenses/LICENSE-rdb, scripts/release/licenses/LICENSE-sarama, scripts/release/licenses/LICENSE-siddontang-rdb, scripts/release/licenses/LICENSE-snappy, scripts/release/licenses/LICENSE-speakeasy, scripts/release/licenses/LICENSE-speakeasy-windows, scripts/release/licenses/LICENSE-urfave-cli, scripts/release/licenses/LICENSE-widuu-gojson, scripts/release/licenses/LICENSE-x2j
=> [SCB-771] Add missing dependencies in LICENSE

frontend/app/scripts/modules/topology/controllers/topologyCtrl.js
=> Fix topology bug for multiple versions

pkg/util/net.go, server/api.go, server/service/instance.go, server/service/microservice.go
=> SCB-776 Log print more detailed

frontend/app/scripts/modules/dashboard/controllers/dashboardCtrl.js, frontend/app/scripts/modules/dashboard/views/dashboard.html
=> Make Instance statistics non-clickable

glide.yaml
=> SCB-816 Update the protobuf version to 1.0.0

server/metric/calculator.go, server/metric/calculator_test.go, server/metric/common.go, server/metric/common_test.go, server/metric/gatherer.go, server/metric/gatherer_test.go, server/metric/reporter.go, server/metric/reporter_test.go
=> SCB-792 More abundant metrics information

docs/README.md, integration/docker/README.md, integration/docker/docker-compose.yml, integration/docker/prometheus.yml, integration/integrationtest_suite_test.go, integration/k8s/README.md, integration/k8s/service-center/.helmignore, integration/k8s/service-center/Chart.yaml, integration/k8s/service-center/charts/etcd/Chart.yaml, integration/k8s/service-center/charts/etcd/templates/_helpers.tpl, integration/k8s/service-center/charts/etcd/templates/deployment.yaml, integration/k8s/service-center/charts/etcd/values.yaml, integration/k8s/service-center/templates/NOTES.txt, integration/k8s/service-center/templates/_helpers.tpl, integration/k8s/service-center/templates/deployment.yaml, integration/k8s/service-center/templates/ingress.yaml, integration/k8s/service-center/templates/service.yaml, integration/k8s/service-center/values.yaml, scripts/build/tools.sh, scripts/docker/build-frontend-image/start.sh, scripts/docker/build-image/start.sh, server/api.go, server/core/proto/services.go, server/server.go
=> SCB-815 Support deploy in Kubernetes

pkg/util/sys.go, pkg/util/util_test.go, scripts/build/tools.sh, server/infra/quota/quota.go, server/plugin/infra/quota/buildin/buildin.go, server/plugin/infra/quota/buildin/common.go, server/plugin/infra/quota/unlimit/unlimit.go, server/service/microservice_test.go, server/service/rule_test.go, server/service/schema_test.go, server/service/tag_test.go
=> SCB-840 Support configable limit in buildin quota plugin

.travis.yml
=> SCB-844 Upgrade CI to go 1.9.2

server/service/dependency_test.go, server/service/util/dependency_query.go
=> SCB-851 BUG: Can not get providers if consumer have * dependency rule

pkg/chain/callback.go, pkg/chain/chain.go, pkg/chain/chain_test.go, pkg/chain/invocation.go, server/admin/model/dump.go, server/admin/service.go, server/core/swagger/v4.yaml, server/rest/controller/v4/main_controller.go
=> SCB-797 More information in dump API

scripts/build/tools.sh
=> SCB-863 build script for docker image gives an error

docker-compose.yml, integration/docker/docker-compose.yml, integration/k8s/service-center/templates/deployment.yaml, scripts/docker/build-frontend-image/README.md, scripts/docker/build-frontend-image/start.sh
=> SCB-862 Using different environment variables in image

server/service/util/dependency_util.go
=> SCB-857 Provider rule of consumer can not be removed

frontend/app/scripts/modules/dashboard/controllers/dashboardCtrl.js, frontend/app/scripts/modules/serviceCenter/controllers/servicesListCtrl.js
=> [SCB-808]Aut-refresh the dashboard and service-list page every 10sec

server/plugin/infra/registry/embededetcd/embededetcd.go
=> SCB-890 Lost changed event when bootstrap with embedded etcd

pkg/util/map.go, pkg/util/map_test.go, server/admin/model/dump.go, server/admin/service.go, server/core/config.go, server/core/microservice.go, server/core/proto/common.go, server/core/proto/services.go, server/core/proto/types.go, server/govern/govern_suite_test.go, server/govern/service.go, server/plugin/infra/quota/buildin/buildin.go, server/plugin/infra/quota/buildin/common.go, server/plugin/plugin.go, server/plugin/plugin_test.go, server/server.go, server/service/microservice.go, server/service/service.go, server/service/service_suite_test.go
=> SCB-892 Output plugins configs in version api

server/plugin/infra/registry/etcd/etcd_test.go
=> SCB-850 Support discover instances from kubernetes cluster

server/plugin/infra/registry/embededetcd/embededetcd.go, server/plugin/infra/registry/etcd/etcd.go, server/plugin/infra/registry/etcd/etcd_test.go, server/service/microservice.go, server/service/microservice_test.go
=> SCB-901 Making service registration api idempotent

.gitignore, README.md, go.mod
=> SCB-899 Support go1.11 module maintaining

scripts/build/local.sh, scripts/release/make_release.sh, server/infra/discovery/common.go, server/infra/discovery/config.go, server/infra/discovery/config_test.go, server/plugin/infra/discovery/etcd/cacher_kv.go, server/plugin/infra/discovery/etcd/cacher_kv_test.go, server/plugin/infra/discovery/etcd/common.go, server/service/notification/processor_test.go
=> SCB-924 Etcd cacher should re-list etcd in fixed time interval

glide.yaml, go.mod, pkg/client/sc/apis.go, pkg/client/sc/client.go, scctl/pkg/plugin/README.md, scctl/pkg/plugin/diagnose/diagnose.go, scctl/pkg/plugin/get/instance/instance_cmd.go, scctl/pkg/plugin/get/instance/types.go, scctl/pkg/plugin/get/schema/schema_cmd.go, scctl/pkg/plugin/get/schema/types.go, scctl/pkg/plugin/get/service/service_cmd.go, scctl/pkg/plugin/get/service/types.go, scctl/pkg/plugin/version/cmd.go, scctl/pkg/progress-bar/progress-bar.go, scripts/release/LICENSE, scripts/release/licenses/LICENSE-cheggaaa-pb, server/core/key_convertor.go, server/core/microservice.go, server/service/instance.go
=> SCB-914 Support using scctl to download schemas

server/service/instance.go, server/service/microservice.go, server/service/rule.go, server/service/tag.go
=> SCB-929 Concurrent error in update resource APIs

frontend/app/scripts/modules/serviceCenter/controllers/schemaCtrl.js
=> SCB-930 Make Regex more stringent to remove new line char from Schema

server/infra/discovery/cache_kv.go, server/infra/discovery/cache_test.go
=> SCB-934 sc  will panic when get all dependency rules

scctl/pkg/plugin/README.md, server/plugin/infra/tracing/buildin/common.go, server/plugin/infra/tracing/buildin/common_test.go
=> SCB-937 Customizable tracing sample rate

server/core/backend/common.go, server/core/backend/defer_instance.go
=> SCB-938 Should check self presevation max ttl

scctl/pkg/plugin/README.md, scctl/pkg/plugin/get/cmd.go
=> SCB-951 Wrong help information in scctl

server/core/backend/defer_instance.go, server/core/backend/defer_test.go
=> SCB-958 The instance delete event delay more than 2s

docs/helm.md, server/plugin/pkg/discovery/k8s/adaptor/cacher_index.go, server/plugin/pkg/discovery/k8s/adaptor/cacher_instance.go, server/plugin/pkg/discovery/k8s/adaptor/cacher_service.go, server/plugin/pkg/discovery/k8s/adaptor/common.go, server/plugin/pkg/discovery/k8s/adaptor/convertor.go
=> SCB-972 Using Sha1 signature key as UUID of k8s service

server/core/key_convertor.go, server/core/key_convertor_test.go, server/service/dependency_test.go, server/service/event/service_event_handler.go, server/service/event/tag_event_handler.go, server/service/instance.go, server/service/util/dependency_util.go
=> SCB-977 Dependencies will not be updated in 5min when re-create provider service

server/service/instance_test.go, server/service/instance_validator.go, server/service/microservice_test.go, server/service/microservice_validator.go
=> SCB-981 Can not remove the microservice and instance properties

server/service/util/dependency.go, server/service/util/dependency_test.go, server/service/util/dependency_util.go
=> SCB-980 The dependency will be broken when commit etcd failed

pkg/client/sc/apis.go, pkg/client/sc/client.go, pkg/client/sc/config.go, pkg/task/service_test.go, scctl/bootstrap/bootstrap.go, scctl/pkg/cmd/cmd.go, scctl/pkg/plugin/README.md, scctl/pkg/plugin/health/cmd.go
=> SCB-984 Add Health Check command

server/metric/calculator.go, server/metric/calculator_test.go, server/metric/metrics.go, server/metric/metrics_test.go, server/metric/reporter.go, server/plugin/pkg/discovery/etcd/metrics_test.go, server/rest/metrics.go, server/rest/reporter.go
=> SCB-983 Output the QPS per domain

README.md, frontend/Readme.md, scctl/README.md
=> SCB-435 Update README

server/core/core.go
=> SCB-991 Optimize args parsing

.gitignore
=> SCB-993 Add sc binary to .gitignore

frontend/app/scripts/modules/serviceCenter/controllers/schemaCtrl.js
=> SCB-993 Can not test Schema if instance port greater than 4 digits

pkg/client/sc/apis.go, pkg/client/sc/client_lb.go, pkg/lb/loadbalancer.go, pkg/lb/loadbalancer_test.go, pkg/lb/roundrobin.go, pkg/rest/client.go, scctl/pkg/cmd/cmd.go, server/plugin/pkg/discovery/servicecenter/aggregate.go
=> SCB-988 Add loadbalancer in sc client

pkg/util/context.go, pkg/util/context_grpc.go, pkg/util/context_grpc_test.go, server/handler/context/v3.go, server/handler/context/v4.go, server/rest/controller/v4/instance_controller.go, server/service/instance.go
=> SCB-994 SC can not read the context when client using grpc api

pkg/client/sc/client.go, pkg/client/sc/config.go, server/admin/model/dump.go, server/admin/service.go, server/core/key_convertor.go, server/plugin/pkg/discovery/aggregate/adaptor.go, server/plugin/pkg/discovery/aggregate/cache.go, server/plugin/pkg/discovery/aggregate/conflict_checker.go, server/plugin/pkg/discovery/aggregate/indexer.go, server/plugin/pkg/discovery/etcd/cacher_kv.go, server/plugin/pkg/discovery/indexer_cache.go, server/plugin/pkg/discovery/k8s/adaptor/convertor.go, server/plugin/pkg/discovery/servicecenter/adaptor.go, server/plugin/pkg/discovery/servicecenter/aggregate.go, server/plugin/pkg/discovery/servicecenter/cacher.go, server/plugin/pkg/discovery/servicecenter/cluster.go, server/plugin/pkg/discovery/servicecenter/indexer.go, server/plugin/pkg/discovery/types.go, server/plugin/pkg/discovery/types_test.go, server/service/event/service_event_handler.go, server/service/instance.go, server/service/instance_test.go
=> SCB-993 print warning log when aggregate conflict

server/plugin/pkg/registry/etcd/etcd_test.go, server/service/microservice_test.go, server/service/util/versionrule.go, server/service/util/versionrule_test.go
=> SCB-1015 Support the forth microservice version number registration

server/admin/admin_suite_test.go, server/core/microservice.go, server/govern/govern_suite_test.go, server/handler/cache/cache.go, server/plugin/pkg/discovery/aggregate/adaptor.go, server/plugin/pkg/discovery/aggregate/common.go, server/plugin/pkg/discovery/aggregate/indexer.go, server/plugin/pkg/discovery/servicecenter/aggregate.go, server/plugin/pkg/discovery/servicecenter/aggregate_test.go, server/plugin/pkg/discovery/servicecenter/indexer.go, server/plugin/pkg/discovery/servicecenter/indexer_test.go, server/plugin/pkg/registry/common.go, server/plugin/pkg/registry/config.go, server/plugin/pkg/registry/option.go, server/service/util/common.go, server/service/util/util.go
=> SCB-993 Fixed the error of microservice registration in multi-dc

frontend/app/apiList/apiList.js, frontend/app/scripts/languages/locale-en.js, frontend/app/scripts/languages/locale-zh.js, frontend/app/scripts/modules/serviceCenter/controllers/serviceInfoCtrl.js, frontend/app/scripts/modules/serviceCenter/views/serviceInfo.html, frontend/app/scripts/modules/serviceCenter/views/serviceProperties.html, frontend/app/scripts/scRouterConfig.js, frontend/app/scripts/views/index.html, frontend/app/styles/main.css
Preview : 
No Properties View : 
https://github.com/apache/servicecomb-service-center/issues/489
---
=> SCB-1025 Add Properties View in Service Info Page

docs/integration-grafana.md, scripts/release/make_release.sh
=> SCB-1027 Fix the core dump in SC which compiled with go1.10+

examples/infrastructures/docker/docker-compose.yml, scripts/docker/README.md
=> SCB-993 Update the document of docker-compose

frontend/Readme.md, scctl/README.md, scctl/pkg/plugin/README.md
=> SCB-993 Add the requirement of scctl

scctl/pkg/plugin/version/cmd.go
=> SCB-1041 scctl version command does not print sc verison

pkg/log/log.go, pkg/log/log_zap.go
=> SCB-1052 Import zap logger without binding go version

glide.yaml, go.mod, pkg/client/sc/config.go, pkg/rest/client.go, pkg/rest/common.go, pkg/rest/server.go, scripts/release/LICENSE, server/plugin/pkg/discovery/servicecenter/aggregate.go, server/plugin/pkg/registry/common.go, server/plugin/pkg/registry/config.go, server/rest/server.go
=> SCB-1032 Support compress the response

server/metric/calculator.go, server/metric/gatherer.go, server/metric/metrics.go, server/metric/metrics_test.go
=> SCB-1050 Metrics cache is not clean

integration/instances_test.go, server/core/proto/batch_find.go, server/core/proto/services.go, server/core/proto/types.go, server/core/swagger/v4.yaml, server/plugin/pkg/discovery/aggregate/repo.go, server/plugin/pkg/discovery/etcd/repo.go, server/plugin/pkg/discovery/servicecenter/repo.go, server/plugin/pkg/registry/config.go, server/rest/controller/v4/instance_controller.go, server/service/instance.go, server/service/instance_test.go, server/service/instance_validator.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go, server/service/validate.go
=> SCB-1053 Batch microservices instances discovery API 

server/plugin/pkg/discovery/etcd/cacher_kv.go, server/plugin/pkg/discovery/etcd/cacher_kv_test.go, server/plugin/pkg/discovery/etcd/common.go
=> SCB-1059 unexpected events publish if error occurs in previous list-watch loop

server/core/proto/batch_find.go
=> SCB-1053 Allow instances to be nil

server/core/swagger/v4.yaml
=> SCB-1059 Update the api doc

server/core/backend/discovery.go, server/service/instance.go, server/service/instance_test.go, server/service/util/heartbeat_util.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go
=> SCB-1059 Re-register instance does not keep alive the lease

integration/apis.go, integration/instances_test.go, server/core/swagger/v4.yaml, server/rest/controller/v4/dependency_controller.go, server/rest/controller/v4/instance_controller.go, server/rest/controller/v4/microservice_controller.go, server/rest/controller/v4/query_rule_controller.go, server/rest/controller/v4/schema_controller.go, server/rest/controller/v4/tag_controller.go, server/service/instance.go, server/service/instance_test.go
=> SCB-1053 Update the batch find API

pkg/notify/notice.go, pkg/notify/notification_test.go, pkg/time/time.go, pkg/time/time_test.go, server/core/backend/lease.go, server/core/backend/lease_test.go
=> SCB-1092 Use a simple time struct to save memory

integration/health-metrics-grafana.json, pkg/notify/notification_service.go, pkg/notify/types.go, pkg/util/sys.go, pkg/util/sys_test.go, server/alarm/common.go, server/alarm/service.go, server/core/microservice.go, server/core/microservice_test.go, server/health/metrics.go, server/notify/stream.go, server/notify/websocket.go
=> SCB-1059 Bug fixes

server/plugin/pkg/quota/buildin/buildin.go, server/plugin/pkg/quota/buildin/common.go, server/plugin/pkg/quota/buildin/counter.go, server/plugin/pkg/quota/buildin/counter_test.go, server/plugin/pkg/quota/counter/counter.go, server/plugin/pkg/quota/counter/event.go, server/plugin/pkg/quota/counter/event_test.go, server/service/event/instance_event_handler.go, server/service/util/instance_util.go
=> SCB-1059 Optimize quota plugin

integration/health-metrics-grafana.json, pkg/buffer/reader.go, pkg/buffer/reader_test.go, pkg/client/sc/client_lb.go, pkg/client/sc/client_lb_test.go, pkg/notify/notice.go, pkg/notify/notice_test.go, pkg/rest/client.go, server/notify/listwatcher.go, server/notify/metrics.go, server/notify/stream.go, server/notify/stream_test.go, server/notify/websocket.go, server/plugin/pkg/discovery/cacher.go, server/plugin/pkg/discovery/etcd/cacher_kv.go, server/plugin/pkg/discovery/metrics.go, server/plugin/pkg/discovery/types.go, server/service/event/instance_event_handler.go, server/service/event/rule_event_handler.go, server/service/event/tag_event_handler.go
=> SCB-1092 Output event processing time

pkg/client/sc/instance.go, pkg/client/sc/microservice.go, pkg/client/sc/watch.go, pkg/client/sc/websocket.go
=> Issues-531 add registration and discovery for client

pkg/rest/client.go, server/plugin/pkg/registry/etcd/common.go, server/plugin/pkg/registry/etcd/etcd.go
=> SCB-1059 Add grpc keepalive time

integration/health-metrics-grafana.json, server/notify/common.go, server/notify/metrics.go, server/notify/stream.go, server/notify/websocket.go
=> SCB-1092 More abundant metrics information

README.md
=> [DOCS] Fix word

syncer/serf/agent.go, syncer/serf/agent_test.go, syncer/server/handler.go, syncer/server/server.go
Change the startup process of the syncer's services for subsequent cluster management
---
=> [SCB-1301]Change the startup process of the syncer's services for subsequent cluster management

syncer/cmd/root.go, syncer/syncer.go
Signed-off-by: Zen Lin <linzhinan@huawei.com>
---
=> Add License header to syncer/cmd/root.go and syncer/syncer.go

syncer/etcd/storage.go
=> Save syncdata to etcd

server/service/instance.go
=> support env overwrite all instance ttl

syncer/etcd/agent.go, syncer/pkg/mock/mocksotrage/etcd.go, syncer/server/server.go, syncer/servicecenter/servicecenter.go, syncer/servicecenter/servicecenter_test.go, syncer/servicecenter/storage/storage.go
=> [SCB-1427] Move storage to syncer/servicecenter

syncer/servicecenter/storage/operation.go, syncer/servicecenter/storage/storage.go
=> [SCB-1429] Abstract storage operation

syncer/cmd/daemon.go, syncer/config/config.go, syncer/plugins/eureka/eureka.go, syncer/plugins/eureka/instance.go, syncer/plugins/eureka/service.go, syncer/plugins/eureka/transform.go, syncer/plugins/eureka/type.go, syncer/plugins/servicecenter/transform.go
=> [SCB-1453] Add new servicecenter plugin supported eureka

scripts/prepare_env_ut.sh, scripts/ut.sh, server/core/config.go, server/core/proto/types.go, server/mux/mux.go, server/server.go, server/service/event/dependency_event_handler.go, server/service/util/microservice_util.go, server/task/clear_service.go, server/task/clear_service_test.go
=> Clear no-instance services automatically

go.mod, syncer/cmd/daemon.go, syncer/config/config.go, syncer/config/config_test.go, syncer/config/tlsconfig.go, syncer/grpc/client.go, syncer/grpc/server.go, syncer/serf/config.go, syncer/server/handler.go, syncer/server/server.go
=> [SCB-1441] [Syncer] Support for tls certificates when using GRPC for data synchronization

syncer/cmd/daemon.go, syncer/config/config.go, syncer/pkg/mock/mockplugin/servicecenter.go, syncer/plugins/eureka/eureka.go, syncer/plugins/option.go, syncer/plugins/plugin_test.go, syncer/plugins/servicecenter.go, syncer/plugins/servicecenter/servicecenter.go, syncer/plugins/servicecenter/servicecenter_test.go, syncer/server/server.go, syncer/servicecenter/servicecenter.go, syncer/servicecenter/servicecenter_test.go
=> [SCB-1441] [Syncer] Support for tls certificates when loading instance data from servicecenter

pkg/log/zap.go
=> Use local time in backup log files

server/plugin/pkg/registry/etcd/etcd.go, server/plugin/pkg/registry/etcd/etcd_test.go
=> Bugfix: data decreasing causes panic during paging

syncer/samples/multi-servicecenters/eureka/account-server/pom.xml, syncer/samples/multi-servicecenters/eureka/account-server/src/main/java/org/apache/servicecomb/servicecenter/account/AccountApplication.java, syncer/samples/multi-servicecenters/eureka/account-server/src/main/java/org/apache/servicecomb/servicecenter/account/AccountController.java, syncer/samples/multi-servicecenters/eureka/account-server/src/main/resources/application.yaml, syncer/samples/multi-servicecenters/eureka/eureka-server/pom.xml, syncer/samples/multi-servicecenters/eureka/eureka-server/src/main/java/org/apache/servicecomb/servicecenter/eurekaserver/EurekaServerApplication.java, syncer/samples/multi-servicecenters/eureka/eureka-server/src/main/resources/application.yaml, syncer/samples/multi-servicecenters/eureka/pom.xml, syncer/samples/multi-servicecenters/servicecenter/hello-server/conf/microservice.yaml, syncer/samples/multi-servicecenters/servicecenter/hello-server/main.go, syncer/samples/multi-servicecenters/servicecenter/hello-server/servicecenter/config.go, syncer/samples/multi-servicecenters/servicecenter/hello-server/servicecenter/servicecenter.go
=> [SCB-1491] Example of instance access between multiple service-centers

syncer/samples/multi-servicecenters/eureka/account-server/src/main/java/org/apache/servicecomb/servicecenter/account/AccountController.java, syncer/samples/multi-servicecenters/servicecenter/hello-server/conf/microservice.yaml, syncer/samples/multi-servicecenters/servicecenter/hello-server/main.go, syncer/samples/multi-servicecenters/servicecenter/hello-server/servicecenter/servicecenter.go
=> [SCB-1491] Add retry of descovery and some logs to samples

server/service/microservice.go, server/service/schema.go, server/service/schema_test.go, server/service/service.go
Supply an env variable to control whether to allow the schema modification of services in production environment.
---
=> [SCB-1498] Allow schema modification of services in production environment

pkg/rest/client.go, pkg/rest/common.go, pkg/rest/roa.go, pkg/rest/route.go, pkg/rest/server.go, server/handler/auth/auth.go, server/handler/cache/cache.go, server/handler/context/context.go, server/handler/maxbody/maxbody.go, server/handler/metric/metric.go, server/handler/tracing/tracing.go, server/rest/handler.go
---
Allow different APIs to use different, customizable handler chains
=> [SCB-1512] Allow custom handler chain.

syncer/cmd/version.go, syncer/version/version.go
=> [SCB-1539] [Syncer] Add command line to support output syncer version

server/plugin/export.go, server/plugin/pkg/discovery/aggregate/adaptor.go, server/plugin/plugin.go, server/plugin/types.go
=> Add comments for plugin pkg, to be easier to understand the code

syncer/config/tlsconfig.go, syncer/server/handler.go
=> Fix bug: the tlsConfig used wrong

server/core/backend/defer_instance.go, server/plugin/pkg/discovery/aggregate/adaptor.go, server/plugin/pkg/discovery/aggregate/cache.go, server/plugin/pkg/discovery/aggregate/conflict_checker.go, server/plugin/pkg/discovery/aggregate/indexer.go, server/plugin/pkg/discovery/cache.go, server/plugin/pkg/discovery/cache_kv.go, server/plugin/pkg/discovery/cache_null.go, server/plugin/pkg/discovery/cacher.go, server/plugin/pkg/discovery/config_test.go, server/plugin/pkg/discovery/defer.go, server/plugin/pkg/discovery/discovery.go, server/plugin/pkg/discovery/etcd/adaptor.go, server/plugin/pkg/discovery/etcd/cacher_kv.go, server/plugin/pkg/discovery/etcd/indexer_cache.go, server/plugin/pkg/discovery/etcd/indexer_etcd.go, server/plugin/pkg/discovery/indexer.go, server/plugin/pkg/discovery/indexer_cache.go, server/plugin/pkg/discovery/k8s/adaptor/adaptor.go, server/plugin/pkg/discovery/servicecenter/adaptor.go, server/plugin/pkg/discovery/servicecenter/indexer.go
=> Add comment for cache, add interface CacheReader, to make it easy to understand

etc/conf/app.conf, pkg/gopool/goroutines.go, pkg/util/util_test.go, proxy.sh, server/core/backend/defer_instance.go, server/core/backend/defer_test.go, server/core/backend/discovery.go, server/core/config.go, server/core/proto/parser.go, server/core/proto/parser_test.go, server/core/proto/types.go, server/plugin/pkg/discovery/cache.go, server/plugin/pkg/discovery/cache_kv.go, server/plugin/pkg/discovery/cache_null.go, server/plugin/pkg/discovery/etcd/cacher_kv.go, server/plugin/pkg/discovery/etcd/cacher_kv_test.go, server/plugin/pkg/discovery/indexer_test.go, server/service/util/microservice_util.go
=> SCB-1712 Reset kv cache periodically

etc/conf/app.conf, pkg/log/log_test.go, pkg/log/zap.go, server/bootstrap/bootstrap.go, server/broker/util.go, server/core/config.go, server/core/proto/types.go, server/handler/accesslog/handler.go, server/handler/accesslog/handler_test.go
=> [SCB-1719] Support access log

pkg/rest/client.go, server/plugin/pkg/discovery/aggregate/indexer.go, server/plugin/pkg/discovery/etcd/indexer_cache.go, server/plugin/pkg/discovery/etcd/indexer_etcd.go, server/plugin/pkg/discovery/indexer.go, server/plugin/pkg/discovery/indexer_cache.go, server/plugin/pkg/discovery/servicecenter/indexer.go, server/plugin/pkg/discovery/servicecenter/syncer.go, server/service/cache/filter_consistency.go, server/service/cache/filter_rev.go, server/service/cache/instance.go
=> [SCB-1742] Use cache only when Indexer is not creditable

server/plugin/pkg/registry/etcd/common.go, server/plugin/pkg/registry/etcd/etcd.go
=> Change etcd client MaxCallSendMsgSize to 10MB

go.mod
Fix high CPU usage when disconnected from etcd server
---
=> Upgrade etcd to v3.3.8, improvement: https://github.com/etcd-io/etcd/pull/9840

syncer/etcd/agent.go, syncer/grpc/server.go, syncer/pkg/mock/mocksotrage/etcd.go, syncer/serf/agent.go, syncer/server/server.go
=> [SCB-1788] [Syncer] Change moduleServer interface definition to simplify code

server/govern/README.md
---
修正了readme中的方法名
SC中扩展模块机制的readme对于初学者上手帮助较大，但该readme文件放在govern目录下是否合适，很难找到且与govern关联性不强？放在docs目录下或者server目录下是否更好？
=> fix misspelled words

docs/user-guides/rbac.md, server/handler/auth/auth.go, server/plugin/auth/buildin/buildin.go
=> follow right design pattern of service center

docs/user-guides/rbac.md, go.mod, pkg/errors/text.go, pkg/rbacframe/account.go, pkg/rbacframe/api.go, pkg/rbacframe/api_test.go, pkg/rbacframe/context.go, pkg/rbacframe/error.go, pkg/util/common.go, pkg/validate/matcher.go, pkg/validate/validator.go, server/plugin/auth/buildin/buidlin_test.go, server/plugin/auth/buildin/buildin.go, server/rest/controller/v4/auth_resource.go, server/service/rbac/authr_plugin.go, server/service/rbac/dao/account_dao.go, server/service/rbac/dao/account_dao_test.go, server/service/rbac/dao/resource_dao.go, server/service/rbac/dao/role_dao.go, server/service/rbac/decision.go, server/service/rbac/decision_test.go, server/service/rbac/password.go, server/service/rbac/rbac.go, server/service/rbac/rbca_test.go, server/service/validate.go
---
新增功能：
- 角色和权限通过map先写死，完成最起码的权职分离，admin可以管理账户，developer不可以，但是可以用其余的所有功能。
- 增加了创建用户API，这样admin账户就可以对不同用户分发账户，将用户分离
- 增加了rbac frame包，可以方便其他go语言编写的想进行认证的组件进行servicecomb生态的对接。行成统一认证鉴权
- 强制用户使用强密码
Bug：
- 更改密码也做了强密码校验
- 新老密码不允许相同
其他优化：
- vlidate写的非常糟糕，switch语句会被无限拉长，抽离业务API进行校验
=> build in role permission check

server/service/rbac/rbac.go
=> use plain content when private key decrypted failed

server/rest/controller/v4/auth_resource.go, server/rest/controller/v4/auth_resource_test.go, server/service/rbac/password.go, server/service/rbac/rbca_test.go, server/service/validate.go
---
改动：
- 需要指明更改的目标账号是什么
- 账号名匹配则进入自更改账号逻辑，不匹配进行role权限判断，合格就强制更改命令
- 不对当前密码做合规校验，因为admin角色吊销他人密码时可以为空；自己更改时也不可能不传，最终会做匹配校验
=> change password api refine

go.mod, server/plugin/auth/buildin/buildin.go, server/rest/controller/v4/auth_resource.go, server/rest/controller/v4/auth_resource_test.go, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go, server/service/rbac/password.go, test/test.go
---
新功能：
- 1小时内只允许5次登录尝试，都失败的话block1小时
- 对错误的密码尝试都进行了warn级别日志输出
TODO：
灵活可配置block时间，尝试次数等
局限：
- 没有分布式的限制，也就是说每个sc实例允许一小时内尝试5次，即每小时可以尝试5*实例数
- 按照IP进行block，如果一个很多流量都从一个ip出，将导致整个公司无法访问sc
=> block user brute force login attempts

pkg/rbacframe/api_test.go, pkg/rbacframe/context.go, server/plugin/auth/buildin/buildin.go, server/service/rbac/rbac.go
=> Change auth white list apis

pkg/errors/text.go, pkg/rbacframe/account.go, pkg/rbacframe/resource_dao.go, server/plugin/auth/buildin/buidlin_test.go, server/plugin/auth/buildin/buildin.go, server/rest/controller/v4/auth_resource.go, server/rest/controller/v4/auth_resource_test.go, server/service/kv/store.go, server/service/kv/store_test.go, server/service/rbac/dao/account_dao.go, server/service/rbac/rbac.go, server/service/rbac/rbca_test.go
---
新功能：
- 删除账号
- list账号
- get账号
优化：
- 为每个账号生成唯一ID
- resource映射API，可支持扩展
- 重构了部分代码, 更好的解耦api与resource，让用户只理解resource
=> [RBAC]delete, list account

server/handler/maxbody/maxbody.go
As there is parameter validation, remove API level body limit for service registration, use global limit instead.
---
=> Remove API level body limit for service registration, use global limit instead.

frontend/schema/schemahandler.go, frontend/server.go, server/core/config.go, server/core/proto/types.go, server/rest/controller/v4/schema_controller.go
=> add Schema Disable Config #674

pkg/rbacframe/api_test.go, pkg/rbacframe/context.go, server/service/rbac/rbac.go
=> rbac frame pkg should not import un necessary pkg

Dockerfile.build, README.md, go.sum, scripts/build/local.sh, scripts/docker/build-image/build.sh
=> fix problem: can not build docker

go.mod
---
1. 升级go-chassis，foundation 版本号
2. 去除多余的go.etcd.io/etcd
=> Upgrade go-chassis to v2.0.0

examples/etcd_data_struct.yaml, examples/mongodb_data_struct.yaml
- No significant feature modification leads to no issue related and no SCB pr title
- This pr make a summary for etcd && mongodb data struct
- go build/go fmt/unit test/integration test has all finished or passed
=> [docs] summary of etcd && mongodb data struct

go.mod, go.sum, pkg/registry/registry.pb.go, pkg/util/util.go, scctl/pkg/plugin/get/instance/printer.go, scctl/pkg/plugin/get/schema/schema_cmd.go, scctl/pkg/plugin/get/service/printer.go, server/core/key_convertor.go, syncer/plugins/servicecenter/instance.go, syncer/plugins/servicecenter/instance_test.go, syncer/plugins/servicecenter/schemas.go, syncer/plugins/servicecenter/service.go, syncer/plugins/servicecenter/service_test.go, syncer/plugins/servicecenter/servicecenter.go, syncer/plugins/servicecenter/servicecenter_test.go, syncer/plugins/servicecenter/transform.go, syncer/serf/serf.go, syncer/serf/serf_test.go, syncer/server/server.go
1 Fix bug on running in registry mode of servicecenter 
2. Fix bug on join mechanism
=> Fix bugs on running in Syncer registry mode of servicecenter & join mechanism 

server/service/instance.go
=> Add no dependence when find shared service instances

examples/infrastructures/docker/README.md, server/core/swagger/v4.yaml, server/rest/controller/v4/dependency_controller.go
---
This is a useful api, but the description of the previously deleted restful api document information is not clear. So I added detail description information for all services that consumers rely on. We hope to develop a new UI for ServiceCenter, and hope that when there are new services, the UI will receive real-time push notifications to achieve the goal of "second-level" monitoring.
=>  supplement description of services dependency relation

server/rest/controller/v4/microservice_controller.go, server/service/ms/datasource.go, server/service/ms/etcd/etcd.go, server/service/ms/etcd/etcd_test.go, server/service/ms/etcd/util.go
1. optimize register function according to conversation in https://github.com/apache/servicecomb-service-center/pull/697#discussion_r494841829
2. implement getservice && getservices function
3. finish unit case
#695 
#697
=> [Enhancement] Implement service/ms get service function

server/service/ms/datasource.go, server/service/ms/etcd/etcd.go, server/service/ms/etcd/etcd_test.go, server/service/ms/etcd/util.go
1. implement service/ms/etcd  interface
+ ExistService
+ ModifySchema
+ ModifySchemas
+ ExistSchema
#695 -- **background of the enhancement,**  service/ms interface implement
#697 -- framework of the enhancement
=> [Enhancement] Implement service/ms datasource interface 

pkg/rbacframe/api_test.go, pkg/rbacframe/context.go, pkg/util/util.go, pkg/util/util_test.go, server/handler/context/context.go, server/service/rbac/rbac.go
=> RBAC authentication ignores version and health APIs

server/service/dep/etcd/util.go, server/service/ms/datasource.go, server/service/ms/etcd/etcd.go, server/service/ms/etcd/etcd_test.go, server/service/ms/etcd/util.go, server/service/ms/manager_test.go
[Note] unit test for UnregisterService depends on implementation of RegisterInstance.
+ UpdateService
+ UnregisterService
+ RegisterInstance
+ GetDeleteServiceFunc (for batchDeleteService)
2. add more config item to option file
+  ttl
+ schemaEditable
3. finish ut
#701 -- service/ms interface implement
#697 -- background of the enhancement, service/ms interface implement
#695 -- framework of the enhancement
=> [enhancement] implement ms module interface

server/core/proto/types.go, server/service/rbac/rbac.go
=> Give prompt message of whether open rbac module

server/service/auth/etcd/etcd.go, server/service/auth/etcd/etcd_test.go, server/service/auth/etcd/key_generator.go, server/service/auth/etcd/key_generator_test.go, server/service/lock/datasource.go, server/service/lock/etcd/etcd.go, server/service/lock/etcd/etcd_test.go, server/service/lock/manager.go, server/service/lock/options.go, server/service/lock/types.go
Commit Message
1. implement service/auth/etcd interface
* AccountExist
* GetAccount
* ListAccount
* DeleteAccount
* UpdateAccount
* AddDomain
* DomainExist
* AddProject
* ProjectExist
2. implement service/lock/etcd interface
* NewDLock
=> implement auth lock datasource interface

server/service/ms/datasource.go, server/service/ms/etcd/etcd.go, server/service/ms/etcd/etcd_test.go, server/service/ms/etcd/util.go
+ GetInstance
+ GetInstances
+ FindInstances
+ UpdateInstanceStatus
+ UpdateInstanceProperties
+ UnregisterInstance
+ HeartbeatSet
+ BatchFind
2. finish unit test relative to the instance above
#708 -- optimize service/util func invoker in ms/etcd package
#703  -- service/ms interface implement
#701 -- service/ms interface implement
#697 -- background of the enhancement, service/ms interface implement
#695 -- framework of the enhancement
https://issues.apache.org/jira/browse/SCB-2094
| Module | Lines |
|--------| ------|
| Unit test| 1100|
| Instance logic| 600 |
=> [SCB-2094] implement ms module interface

server/service/dep/datasource.go, server/service/dep/etcd/etcd.go, server/service/dep/etcd/etcd_suite_test.go, server/service/dep/etcd/etcd_test.go
- AddDependency
- CreateDependency
- SearchProviderDependency
- SearchConsumerDependency
#707
=> [SCB-2094] Implement service/dep exist interface

datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/ms.go
1. implement interface
#697 -- background of the enhancement, service/ms interface implement   (popozy)
=> [SCB 2094] implement datasource/ms addTags interface

datasource/etcd/dep_test.go
=> [SCB-2094] Fix dependency ut

datasource/etcd/dep_test.go, datasource/etcd/etcd_suite_test.go, datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/ms.go, scripts/ut_test_in_docker.sh
+ GetSchema
+ GetAllSchema
+ DeleteSchema
+ AddRule
+ GetRule
+ DeleteRule
+ UpdateRule
2. finish unit test relative to the instance above
3. add datasource to unit shell script to make github ci make sense to it
#710 -- implement ms module interface
#708 -- optimize service/util func invoker in ms/etcd package
#703  -- service/ms interface implement
#701 -- service/ms interface implement
#697 -- background of the enhancement, service/ms interface implement
#695 -- framework of the enhancement
| Module | Lines |
|--------| ------|
| Unit test| 900 |
| Schema & Rule implement logic| 600 |
=> [SCB 2094] implement ms module interface

datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/ms.go
1. implement interface
+ GetTags
+ UpdateTag
+ DeleteTags
2. finish unit test relative to the instance above
#714 -- implement datasource/ms addTags interface
#697 -- background of the enhancement, service/ms interface implement (popozy)
=> [SCB 2094] implement datasource/ms tag interface

datasource/dep.go, datasource/etcd/dep.go, datasource/etcd/dep_test.go
- AddOrUpdateDependencies
- SearchProviderDependency
- SearchConsumerDependency
=> [SCB-2094] reImplement service/dep exist interface

datasource/etcd/dep.go, datasource/etcd/key_generator.go, datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/etcd/util.go, datasource/ms.go
1. Implement server/rest/govern exist interface
- GetServiceDetail
- GetServicesInfo
- GetApplications
=> [SCB-2094] Implement server/rest/govern exist interface

datasource/etcd/ms.go, datasource/ms.go, pkg/registry/struct.go
=> SCB-2094 Add list provider instances APIs

datasource/etcd/system.go, datasource/etcd/system_test.go, datasource/system.go
=> SCB-2094 Add system management APIs

etc/conf/app.yaml, go.mod, go.sum, scripts/release/licenses/LICENSE-iancoleman-strcase, server/command/command.go, server/config/config.go, server/config/config_test.go, server/config/options.go, server/config/types.go, server/config/util.go, server/config/util_test.go
=> SCB-2094 Refactor config

datasource/mongo/account.go, datasource/mongo/dep.go, datasource/mongo/engine.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/system.go
1. Implement mongo datasource interface
- account
- dep
- engine
- mongo
- ms
- system
=> [SCB-2094] Implement mongo datasource interface

README.md, docs/user-guides/metrics.md
=> SCB-2094 Add metrics list

datasource/mongo/heartbeat/healthcheck.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker.go, datasource/mongo/heartbeat/manager.go, datasource/mongo/heartbeat/manager_test.go, datasource/mongo/heartbeat/options.go, datasource/mongo/heartbeat/types.go, datasource/mongo/ms.go
Implementation of Mongo heartbeat plugin
1. heartbeat
2. heartbeatset
---
=> SCB-2094 Implementation of Mongo heartbeat plugin

.github/workflows/golangci-lint.yml
=> SCB-2094 Fix github action deprecating commands

datasource/mongo/account.go, datasource/mongo/account_test.go, datasource/mongo/client/mongo.go, datasource/mongo/database.go
=> SCB-2094 Implement the Mongo account interface

datasource/mongo/account.go, datasource/mongo/account_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker_test.go
=> SCB-2094 Implement of Mongo heartbeat interface

datasource/mongo/account_test.go, datasource/mongo/bootstrap/bootstrap.go, datasource/mongo/mongo.go, datasource/mongo/mongo_suite_test.go, scripts/ut_test_in_docker.sh, server/bootstrap/bootstrap.go
Mongo interface is not fully implemented, the test cases are partially annotated
=> 【SCB-2094】 Adjust Mongo suite test

datasource/etcd/ms.go, datasource/etcd/util/microservice_util.go
=> SCB-2094 Support filter by domain

datasource/account.go, datasource/etcd/account.go, datasource/etcd/etcd.go, datasource/etcd/system.go, datasource/mongo/account.go, datasource/mongo/system.go, datasource/system.go, datasource/types.go, server/resource/v4/auth_resource.go, server/service/rbac/dao/account_dao.go, server/service/rbac/rbac.go
=> SCB-2094 Add Dlock API

etc/conf/app.yaml, server/config/config.go, server/config/server.go
=> SCB-2094 Bug fixes

datasource/mongo/account_test.go, datasource/mongo/client/mongo.go, datasource/mongo/client/mongo_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat_test.go, datasource/mongo/mongo.go, datasource/mongo/ms_test.go, etc/conf/app.conf, go.mod
=> [SCB-2094] implement mongo init client

datasource/mongo/client/mongo.go, datasource/mongo/client/mongo_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat_test.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go
1. remove mongo collections init operation
2. change docexist from count to findone
=> SCB-2094 the mongo collections should not be fixed

.github/PULL_REQUEST_TEMPLATE.md
=> how to raise pr

datasource/dependency_util.go, datasource/mongo/account.go, datasource/mongo/client/common.go, datasource/mongo/client/mongo.go, datasource/mongo/common.go, datasource/mongo/database.go, datasource/mongo/dep.go, datasource/mongo/dep_test.go, datasource/mongo/engine.go, datasource/mongo/heartbeat/common.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker_test.go, datasource/mongo/heartbeat/manager.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go, datasource/mongo/util.go
=> [SCB-2094] implement mongo instance/dependence/engine interface

datasource/mongo/heartbeat/heartbeatchecker/heartbeat.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeat_test.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker.go, datasource/mongo/heartbeat/heartbeatchecker/heartbeatchecker_test.go
- InstanceID is used as a unique index, adding serviceID query conditions will degrade performance
- Adjust the package import order according to the specification
**Performance test situation**
1. Use instanceID and serviceID to update instance data
summary + 138677 in 00:00:20 = 7013.1/s Avg:    14 Min:     0 Max:   157 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary + 212159 in 00:00:30 = 7072.0/s Avg:    14 Min:     0 Max:   154 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary = 350836 in 00:00:50 = 7048.6/s Avg:    14 Min:     0 Max:   157 Err:     0 (0.00%)
summary + 212248 in 00:00:30 = 7074.9/s Avg:    14 Min:     0 Max:   158 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary = 563084 in 00:01:20 = 7058.5/s Avg:    14 Min:     0 Max: …
=> [SCB-2094] Heartbeat interface optimization

datasource/etcd/cache/common.go, datasource/etcd/client/remote/etcd.go, datasource/etcd/engine.go, datasource/etcd/etcd.go, datasource/etcd/ms.go, datasource/mongo/mongo.go, pkg/util/context.go, pkg/util/net.go, server/bootstrap/bootstrap.go, server/config/config.go, server/config/server.go, server/core/microservice.go, server/handler/context/context.go, server/server.go
=> SCB-2094 Bug fixes: Unavailable SSL

datasource/mongo/ms.go, datasource/mongo/ms_test.go
**what did I do** : Since mongo does not implement cache, related queries need to directly access the database
---
**Rule**：
1. First use the domain, project, Environment, AppId, ServiceName and Version fields to query related services; 
2. Then use tag and black and white list fields to filter.
3. Finally, use the filtered serviceid to query related instances.
=> [SCB-2094] Supplemenet UT of instance and problem fix

datasource/mongo/database.go, datasource/mongo/dep.go, datasource/mongo/dep_test.go, datasource/mongo/dependency_query.go, datasource/mongo/ms.go
=> [SCB-2094] add dep UT, implement dep query interface

.github/workflows/golangci-lint.yml, datasource/etcd/util.go, datasource/mongo/client/errortypes.go, datasource/mongo/client/mongo.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go, datasource/mongo/util.go, datasource/ms_util.go
新增:
1. service,rule,schema,tag问题修改及ut补齐
2. mongo初始化增加创建索引动作
todo：
1. ms_test.go中不规范ut名称
2. infof，errof统一整改
=> SCB-2094 add schema/rule/service ut

server/service/gov/kie/validate.go
=> [SCD-2133] fix governance match validate bug

datasource/etcd/bootstrap/bootstrap.go, datasource/etcd/cache/dependency.go, datasource/etcd/cache/instance.go, datasource/etcd/etcd.go, datasource/etcd/event/event.go, etc/conf/app.yaml, server/service/instance_test.go
=> SCB-2094 Fix: nil point exception when start mongo plugin

docs/user-guides/rbac.md, server/resource/v4/role_resource.go
=> extract role_resource duplicate code in method to a public method

frontend/server_test.go, go.mod
=> SCB-2094 Fix Security Vulnerability - Directory Traversal

client/microservice.go, datasource/common.go, datasource/etcd/system.go, datasource/mongo/system.go, datasource/mongo/system_test.go, datasource/system.go, server/rest/admin/service.go, syncer/grpc/grpc.go, syncer/server/handler.go, syncer/servicecenter/servicecenter.go, syncer/servicecenter/sync.go
dumpcache接口实现以及syncer代码优化    
1.实现mongo的dumpcache接口
2.syncer逻辑优化
3.existence接口请求bug修复
4.重构dumpcache接口
=> implement of mongo DumpCache interface and optimization of syncer

pkg/gov/governance.go, server/resource/v1/gov_resource.go, server/service/gov/config_distributor.go, server/service/gov/config_distributor_test.go, server/service/gov/kie/kie_distributor.go, server/service/gov/kie/validate.go, server/service/gov/mock/mock.go
=> [SCD-2133] add new display data interface

datasource/mongo/ms.go, datasource/mongo/sd/listwatch_inner.go, datasource/mongo/sd/mongo_cache.go, datasource/mongo/sd/mongo_cacher.go, datasource/mongo/sd/types.go, datasource/sdcommon/common.go, datasource/sdcommon/types.go
1. change cache from map to go-cache
2. mongo cache support  GetIntances && Findservice
=> [SCB-2094] cache support get instances

.gitignore, frontend/app/apiList/apiList.js
=> SCB-2176 Fix: Remove functions in comment lines

pkg/validate/matcher.go, server/service/validate.go
=> SCB-2176 Fix: Do not print password when invalid

syncer/server/server.go, syncer/servicecenter/servicecenter.go
在处理从其他syncer同步至本地的删除实例事件后，更新mapping的时序问题导致事件错误地加入增量队列中。
修复此问题。
=> fix bugs of syncer

docs/user-guides/rbac.md, pkg/validate/matcher.go
=> restrict the length of password

datasource/etcd/cache/common.go, datasource/etcd/cache/dependency.go, datasource/etcd/cache/filter_consistency.go, datasource/etcd/cache/instance.go, datasource/etcd/sd/aggregate/indexer.go, pkg/notify/notification_service.go
=> SCB-2176 Fix: Inconsistent cache

server/resource/v1/gov_resource.go, server/service/gov/kie/kie_distributor.go, server/service/gov/kie/validate.go, server/service/gov/mock/mock.go
(cherry picked from commit 952e2de3d2b48d17f9de13a05b6c5e9142eb0439)
---
=> [SCD-2133] add scene id / add custome err

datasource/errortypes.go, datasource/etcd/dep.go, datasource/etcd/event/instance_event_handler.go, datasource/etcd/event/rule_event_handler.go, datasource/etcd/event/tag_event_handler.go, datasource/etcd/ms.go, datasource/etcd/util.go, datasource/etcd/util/dependency_query.go, datasource/etcd/util/dependency_test.go, datasource/etcd/util/microservice_util.go, datasource/etcd/util/rule_util.go, datasource/etcd/util/rule_util_test.go, datasource/etcd/util/util_suite_test.go, datasource/mongo/dep.go, datasource/mongo/dependency_query.go, datasource/mongo/event/instance_event_handler.go, datasource/mongo/ms.go, server/broker/service.go, server/broker/util.go
1. 为GetService增加具体错误类型，db中不存在被查询数据GetService返回数据不存在错误。
2. 修改GetService方法相关的返回值判断。
3. 修改GetService相关的ut。
=> GetService optimize

datasource/mongo/dep_util.go, datasource/mongo/event/instance_event_handler.go, datasource/mongo/ms.go, datasource/mongo/rule_util.go, datasource/mongo/rule_util_test.go, server/notify/instance_subscriber.go
TODO：
1. fix revision problem
---
use this example for test
https://github.com/apache/servicecomb-service-center/issues/620
=> support instance subscribe

datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go, server/plugin/quota/buildin/common.go, server/service/tag_test.go
=> SCB-2176 Fix: POST tags should be covered

datasource/dependency_util.go, datasource/mongo/client/mongo.go, datasource/mongo/database.go, datasource/mongo/dep.go, datasource/mongo/dep_test.go, datasource/mongo/dependency_query.go, datasource/mongo/mongo_suite_test.go, datasource/mongo/ms.go, datasource/mongo/sd/types.go
- 添加dep event，在创建dep queue和find instance时创建dep rule
- 添加dep rule clean，创建dep rule之后清理旧rule
- 添加注销服务时删除dep相关信息
=> fix dep rule

datasource/mongo/mongo.go
【Function】
- Set the timeout time of the data in the instance table, which is 60 seconds by default.
【Bug fix】
- When creating composite index in service，need to add domain field.
=> Set the default timeout for instance

go.mod
=> update kie-client ,support batch delete

go.mod
=> upgrad deps

server/server.go
【issue】: #849
【特性/模块名称】：sc 初始化失败，未打印详细错误
【修改内容】：修改错误打印日志逻辑
【自测情况】：ut全部通过
=> [SCB-2094] Fix initialization does not print detail error

datasource/mongo/client/mongo.go, deployments/db.js
1. add mongo db init script
2. print err info when mongo init failed
=> add mongo init script

.gitignore, datasource/etcd/account.go, datasource/mongo/account.go, pkg/pravicy/password.go, server/service/rbac/rbac.go
- 抽password的保护
- rbac初始化失败日志是矛盾的
=> return if err

datasource/mongo/account.go, datasource/mongo/database.go, datasource/mongo/heartbeat/cache/heartbeatcache.go, datasource/mongo/sd/listwatch_test.go, examples/mongodb_data_struct.yaml, go.mod, pkg/rbacframe/account.go
【issue】: #853
【特性/模块名称】：持久化数据结构体中字段bson格式规范化
【修改内容】：bson格式字段单词超过2个应使用_断隔
【自测情况】：ut全部通过
=> [SCB-2094]Bson parsing specification for persistent data

datasource/mongo/client/errortypes.go, datasource/mongo/client/mongo.go, datasource/mongo/mongo.go, datasource/mongo/util.go
=> add ensure index and validate

scripts/ut.sh, scripts/ut_test_in_docker.sh, server/service/dependency_test.go
【issue】: #865 
【特性/模块名称】：开启db为mongo时 server/service 下面的 ut
【修改内容】：开启db为mongo时 server/service 下面的 ut
【自测情况】：ut全部通过
=> [SCB-2094]open server/service ut

datasource/mongo/mongo.go
1. handle create indexes duplicate error
=> handle create index duplicate error

datasource/etcd/client/config.go, datasource/etcd/config.go, datasource/etcd/etcd.go, datasource/options.go, docs/README.md, docs/user-guides.rst, docs/user-guides/data-source.md, etc/conf/app.yaml, scripts/release/start_scripts/linux/start-service-center.sh, server/config/config.go, server/config/server.go, server/server.go
【issue】: #867
【特性/模块名称】：添加配置说明
【修改内容】：
1.  添加了 data-source.md 介绍文档，介绍了db为etcd或mongo个参数解释
2.  将 CompactIndexDelta 与 CompactInterval 参数配置位置移入etcd 内部
3.  修改 README.md 中通过 python 启动服务 ip 填写问题
【自测情况】：ut全部通过
=> [SCB-2094]add data-source.md

docs/conf.py, docs/user-guides/data-source.md
【issue】: #869
【bugfix】：sphinx can't display the table of markdown
【修改内容】：
在Sphinx extension module添加了sphinx_markdown_tables
【自测情况】：ut全部通过
=> [SCB-2094]sphinx can't display the table of markdown

datasource/mongo/mongo.go, deployments/db.js, docs/user-guides/data-source.rst
【issue】: #867
【特性/模块名称】：修改db配置说明
【修改内容】：
1. 将公共的db配置参数抽取，迁移至上层介绍
2. 在db.js文件添加collection表的相关索引
【自测情况】：ut全部通过
=> [SCB-2094] modify data-source.rst and db.js

go.mod, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go
upgrade some deps version to release version
change 6 times to 3 times
=> change brute force password retry time to 3

go.mod
=> bump verion of gorilla/websocket

datasource/mongo/account.go, datasource/mongo/db/types.go, datasource/mongo/dep.go, datasource/mongo/dep_util.go, datasource/mongo/dependency_query.go, datasource/mongo/engine.go, datasource/mongo/event/instance_event_handler.go, datasource/mongo/event/instance_event_handler_test.go, datasource/mongo/heartbeat/cache/heartbeat.go, datasource/mongo/heartbeat/cache/heartbeat_test.go, datasource/mongo/heartbeat/cache/heartbeatcache_test.go, datasource/mongo/heartbeat/checker/heartbeat.go, datasource/mongo/heartbeat/checker/heartbeat_test.go, datasource/mongo/heartbeat/checker/heartbeatchecker_test.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go, datasource/mongo/role.go, datasource/mongo/rule_util.go, datasource/mongo/rule_util_test.go, datasource/mongo/sd/listwatch_inner.go, datasource/mongo/sd/listwatch_test.go, datasource/mongo/sd/mongo_cacher.go, datasource/mongo/sd/mongo_cacher_test.go, datasource/mongo/sd/types.go, datasource/mongo/system.go, datasource/mongo/system_test.go, datasource/mongo/util.go
【issue】: #884
【特性/模块名称】：循环依赖导致重构
【修改内容】：
1. 将 datasource/mongo/datasource.go 文件移到 datasource/mongo/db下面，并修改其他代码中的相关依赖
2. 将 datasource/mongo/sd/types.go 中的service和instance结构体剔除（冗余）
【自测情况】：ut全部通过
=> [SCB-2094] Move the database.go to mongo/db

datasource/etcd/client/buildin/buildin.go, datasource/etcd/client/embedded/embededetcd.go, datasource/etcd/client/manager.go, datasource/etcd/client/options.go, datasource/etcd/client/remote/etcd.go, datasource/etcd/client/remote/etcd_test.go, datasource/etcd/client/types.go, datasource/etcd/etcd.go, datasource/etcd/sd/aggregate/adaptor.go, datasource/etcd/sd/manager.go, datasource/etcd/sd/manager_test.go, datasource/etcd/sd/options.go, datasource/etcd/sd/types.go, datasource/manager.go, datasource/mongo/heartbeat/common.go, datasource/options.go, datasource/types.go, go.mod, server/server.go, test/test.go
=> refactor, remove unuseful code

datasource/mongo/client/mongo.go, datasource/mongo/client/mongo_test.go, datasource/mongo/event/instance_event_handler_test.go, datasource/mongo/heartbeat/cache/heartbeat_test.go, datasource/mongo/heartbeat/checker/heartbeat_test.go, go.mod
【issue】: #892 
【特性/模块名称】：mongo uri需要支持cipher加密
【修改内容】：
创建mongo连接时，对其url进行解密
【自测情况】：ut全部通过
=> [SCB-2094] Mongo URI uses cipher for encryption

datasource/mongo/account.go, datasource/mongo/dep.go, datasource/mongo/dep_util.go, datasource/mongo/dependency_query.go, datasource/mongo/engine.go, datasource/mongo/event/instance_event_handler.go, datasource/mongo/event/instance_event_handler_test.go, datasource/mongo/heartbeat/cache/heartbeat.go, datasource/mongo/heartbeat/cache/heartbeat_test.go, datasource/mongo/heartbeat/cache/heartbeatcache_test.go, datasource/mongo/heartbeat/checker/heartbeat.go, datasource/mongo/heartbeat/checker/heartbeat_test.go, datasource/mongo/heartbeat/checker/heartbeatchecker_test.go, datasource/mongo/model/types.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/mongo/ms_test.go, datasource/mongo/role.go, datasource/mongo/rule_util.go, datasource/mongo/rule_util_test.go, datasource/mongo/sd/listwatch_inner.go, datasource/mongo/sd/listwatch_test.go, datasource/mongo/sd/mongo_cacher.go, datasource/mongo/sd/mongo_cacher_test.go, datasource/mongo/system.go, datasource/mongo/system_test.go, datasource/mongo/util.go, datasource/mongo/util/db.go, datasource/mongo/util/errors.go, datasource/mongo/util/string.go
【issue】: #884
【特性/模块名称】：database/mongo 目录文件重构 
【修改内容】：
1. 将db修改成model，并做相关适配
2. 抽取一些公共函数到 util 目录
【自测情况】：ut全部通过
=> [SCB-2094] Restructure database/mongo

server/service/rbac/rbac.go
=> password can be decrypted

datasource/etcd/account.go, datasource/mongo/account.go, go.mod, pkg/privacy/password.go, pkg/privacy/password_test.go, server/service/rbac/authr_plugin.go, server/service/rbac/password.go, server/service/rbac/rbac_test.go
=> use scrypt to hash password

pkg/privacy/password.go
=> bug fix: wont print log, it password is wrong

integration/tags_test.go, server/service/tag_test.go, server/service/tag_validator.go
=> SCB-2176 Fix: Allow erase tags

.github/workflows/static_check.yml, scripts/ut.sh, scripts/ut_test_in_docker.sh
【issue】: #900
【特性/模块名称】：UT并发执行
【修改内容】：
静态检查跑UT时将 etcd 和 mongo 并发执行
【自测情况】：ut全部通过
=> [SCB-2094] Adjust ut concurrent execution

server/rest/govern/service.go
=> remove schemas and props response, no client use it

datasource/etcd/util.go, datasource/etcd/util/instance_util.go, datasource/etcd/util/instance_util_test.go
=> SCB-2176 Fix: remove all instances properties

go.mod, pkg/rest/common.go, server/broker/controller.go, server/rest/admin/controller_v4.go, server/rest/controller/rest_util.go, server/rest/controller/v4/dependency_controller.go, server/rest/controller/v4/instance_controller.go, server/rest/controller/v4/main_controller.go, server/rest/controller/v4/microservice_controller.go, server/rest/controller/v4/query_rule_controller.go, server/rest/controller/v4/schema_controller.go, server/rest/controller/v4/tag_controller.go, server/rest/govern/controller_v4.go
=> SCB-2176 Fix: Add response obj context value

server/rest/govern/service.go, server/service/instance.go, server/service/util/instance_util.go, server/service/util/instance_util_test.go
=> SCB-2176 revert commits

datasource/etcd/ms.go, datasource/etcd/util.go, datasource/mongo/client/dao/domain.go, datasource/mongo/client/dao/project.go, datasource/mongo/client/model/types.go, datasource/mongo/event/instance_event_handler.go, datasource/mongo/event/schema_summary_event_handler.go, datasource/mongo/event/service_event_handler.go, datasource/mongo/ms.go, etc/conf/app.yaml, server/plugin/quota/quota.go, server/service/instance.go, server/service/microservice.go
【issue】: #913
【特性/模块名称】：配额修改
【修改内容】：
添加service,instance,schema相关事件的handler，处理其创建、插入、删除等操作，通过event来并统计其数量
【自测情况】：ut全部通过
=> [SCB-2094] Add configuration changes for service instance and schema

pkg/privacy/password.go
=> bcrypt has other prefix

datasource/mongo/event/domain_event_handler.go, datasource/mongo/event/service_event_handler.go, etc/conf/app.yaml
【issue】: #913
【特性/模块名称】：配额修改
【修改内容】：
1.添加 domain 事件处理
2.在yaml中添加 rule 和 tag 配置参数，用于在 validate 判断校验
3.修复bug，调试发现创建相同 domain 和 project ，若相同理应不创建
【自测情况】：ut全部通过
=> [SCB-2094] Add configuration changes for tag and rule

docs/dev-guides.rst, docs/dev-guides/profiling.md, pkg/privacy/password_test.go, server/resource/v4/rbac_resource_test.go, server/service/rbac/authr_plugin.go, server/service/rbac/rbac_test.go, test/benchmark/login.json, test/benchmark/login.sh
- add benchmark test case
- remove account existing check
=> increase token signing performance

datasource/etcd/ms.go, datasource/etcd/ms_test.go, datasource/mongo/ms.go, datasource/ms.go, docs/openapi/v4.yaml, go.mod, pkg/proto/service.go, server/rest/govern/controller_v4.go, server/rest/govern/service.go
新增API接口
/v4/:project/govern/statistics
=> 新增统计服务计数api

datasource/mongo/event/instance_event_handler_test.go, go.mod, syncer/client/sync_client_test.go
=> SCB-2176 Fix: remove bou.ke/monkey

datasource/mongo/ms.go
=> SCB-2176 Fix: lose schemas info

datasource/mongo/sd/listwatch_inner.go
the cache should not concern abount refresh_time field change event
=> fix heartbeat trigger update event problem

Dockerfile.build, control-panel/docker-compose.yml, datasource/etcd/sd/etcd/adaptor_test.go, datasource/etcd/version.go, datasource/instance_test.go, etc/conf/app.conf, etc/conf/app.yaml, examples/dev/docker-compose.yaml, scripts/build/local.sh, scripts/build/tools.sh, scripts/docker/build-frontend-image/build.sh, scripts/docker/build-image/build.sh, scripts/release/README.md, scripts/release/make_release.sh, server/config/config.go, server/config/server.go, server/config/types.go, server/config/util.go, server/core/microservice.go, server/core/microservice_test.go, server/resource/v1/gov_resource_test.go, server/service/gov/config_distributor_test.go, server/service/instance_test.go, server/service/rbac/rbac.go
=> SCB-2176 Deprecate app.conf

datasource/mongo/dep_util.go, datasource/mongo/heartbeat/cache/heartbeat.go, datasource/mongo/heartbeat/checker/heartbeat.go
【issue】: #952 
【特性/模块名称】：查询ConsumerIds功能、心跳功能
【修改内容】：
1. 查询ConsumerIds时，data没有找到是正常情况，没必要返回datanotfound问题
2. heatbeat日志打印问题，打印%v 多余
【自测情况】：ut全部通过
=> SCB-2094 BugFix: GetAllConsumerIds method no data processing & heartbeat log problems

datasource/etcd/ms.go, datasource/mongo/ms.go
=> SCB-2176 Fix: Statistics should not contain global services

pkg/gov/governance.go, pkg/gov/governance_test.go, server/resource/v1/gov_resource.go, server/service/gov/config_distributor.go, server/service/gov/config_distributor_test.go, server/service/gov/kie/kie_distributor.go, server/service/gov/mock/mock.go
=> SCB-2176 Fix: Remove config when delete gov match-group

server/metric/prometheus/reporter.go
=> Fix: add metrics config

docs/user-guides.rst, docs/user-guides/ux.rst
=> SCB-2176 Add UX Deploying section

ux/src/app/service-detail/components/invoked-service/invoked-service.component.ts, ux/src/app/service-list/service-list.component.ts
fix: 调用服务/被调用服务无展示
fix: 服务列表过滤应用错误
=> fix: 测试问题修复

pkg/event/bus.go, pkg/event/subscriber.go, server/connection/grpc/stream.go, server/connection/grpc/stream_test.go, server/connection/ws/common.go, server/connection/ws/keepalive.go, server/connection/ws/options.go, server/connection/ws/websocket.go, server/connection/ws/websocket_test.go, server/event/instance_event.go, server/event/instance_subscriber.go
=> SCB-2176 Refactor websocket

server/plugin/auth/buildin/buidlin_test.go, server/resource/v4/auth_resource.go, server/resource/v4/rbac_resource_test.go, server/resource/v4/role_resource.go, server/service/rbac/resource.go
=> SCB-2176 Standardize RBAC APIs

go.mod, go.sum, pkg/rbacframe/api.go, server/resource/v4/rbac_resource_test.go, server/service/rbac/decision.go, server/service/rbac/rbac_test.go
=> SCB-2176 Update CARI

datasource/etcd/ms.go, datasource/mongo/ms.go, datasource/mongo/util.go, server/rest/govern/controller_v4.go
=> SCB-2176 Add env query string

ux/src/app/config-list/pages/config-create/config-create.component.html, ux/src/app/config-list/pages/config-create/config-create.component.ts
close #982
修改创建的配置默认启用
创建配置时添加的标签可删除
标签key唯一
=> fix: 自定义配置优化

docs/user-guides/metrics.md
=> SCB-2176 Update metrics docs

examples/infrastructures/docker/README.md, go.mod, go.sum, integration/health-metrics-grafana.json, integration/instances_test.go, pkg/util/context.go, server/connection/metrics.go, server/connection/ws/websocket.go, server/connection/ws/websocket_test.go, server/event/instance_subscriber.go, server/metric/prometheus/metrics.go, server/metric/prometheus/reporter.go, server/plugin/discovery/etcd/cacher_kv.go, server/plugin/discovery/metrics.go, server/plugin/discovery/servicecenter/common.go, server/service/event/instance_event_handler.go, server/service/util/microservice_util.go
* SCB-2176 Refactor event bus
* SCB-2176 Fix: UT failures
* SCB-2176 Refactor websocket (#980)
* SCB-2176 Refactor websocket
* SCB-2176 Add UTs
* SCB-2176 Fix: UT failures
* SCB-2176 Fix: websocket health check failed
* SCB-2176 Add benchmark for 10K connection
* SCB-2176 Add benchmark for 10K connection
* SCB-2176 Add event metrics
(cherry picked from commit cc0f684449f6606c45c86d53508428a50eb32b84)
---
=> SCB-2176 Refactor websocket (#986)

docs/openapi/v4.yaml
=> 修改rbac api

datasource/etcd/ms.go, datasource/etcd/util/instance_util.go, datasource/instance_test.go, datasource/mongo/client/dao/instance.go, datasource/mongo/heartbeat/cache/heartbeat.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/ms.go, docs/user-guides.rst, docs/user-guides/data-source.rst, docs/user-guides/heartbeat.rst, etc/conf/app.yaml, pkg/proto/service_ex.go, pkg/rbacframe/api.go, server/alarm/common.go, server/connection/hbws/websocket.go, server/connection/hbws/websocket_test.go, server/connection/ws/websocket.go, server/connection/ws/websocket_test.go, server/event/instance_subscriber.go, server/metrics/connection.go, server/rest/controller/v4/instance_watcher.go, server/server.go, server/service/watch.go
【issue】: #954 
【特性/模块名称】：添加实例心跳websock连接方法
【修改内容】：
1. 添加实例是否存在的接口
2. websocket的心跳接口
【自测情况】：ut全部通过
=> SCB-2094 Add heartbeat ws interface

server/connection/ws/websocket_test.go
=> SCB-2176 Fix: UT panic

server/connection/ws/websocket.go, server/connection/ws/websocket_test.go, server/event/instance_subscriber.go
=> SCB-2176 Resolve comments

server/command/command.go
=> fix bug: rbac can not be enable

datasource/account.go, docs/openapi/v4.yaml, pkg/rbacframe/api.go, server/resource/v4/auth_resource.go, server/resource/v4/rbac_resource_test.go, server/resource/v4/role_resource.go, server/rest/controller/rest_util.go, server/service/rbac/dao/account_dao.go, server/service/rbac/dao/account_dao_test.go, server/service/rbac/dao/role_dao.go, server/service/rbac/rbac.go, server/service/rbac/rbac_test.go, server/service/validate.go
=> Realize all rbac APIs.

server/resource/v4/auth_resource.go, server/rest/govern/service.go, server/service/dependency.go, server/service/instance.go, server/service/microservice.go, server/service/rbac/rbac.go, server/service/rule.go, server/service/schema.go, server/service/tag.go, server/service/validator/dependency_validator.go, server/service/validator/instance_validator.go, server/service/validator/microservice_validator.go, server/service/validator/rule_validator.go, server/service/validator/schema_validator.go, server/service/validator/tag_validator.go, server/service/validator/validator.go, server/service/validator/validator_test.go
对创建账号进行校验：
- 校验account name
- 校验 role字段
重构包结构
=> validate account creation

pkg/util/wildcard.go, pkg/util/wildcard_test.go, server/response/response.go, server/response/response_test.go
=> SCB-2176 Support wildcard filter

server/plugin/auth/auth.go, server/plugin/auth/buildin/buildin.go, server/plugin/auth/buildin/parser.go
=> SCB-2176 Fix: wrong type definition

server/resource/v4/role_resource.go, server/service/validator/rbac_validator.go, server/service/validator/rbac_validator_test.go, server/service/validator/validator.go
=> validate role name

pkg/util/wildcard.go, pkg/util/wildcard_test.go, server/bootstrap/bootstrap.go, server/plugin/auth/buildin/buildin.go
=> SCB-2176 Fix: wildcard bug and service not found in resource parser

pkg/util/context.go, server/handler/auth/auth.go
=> SCB-2176 Fix nil or string type response should not do filter

pkg/rest/util.go, server/plugin/auth/buildin/parser.go, server/plugin/auth/buildin/parser_test.go, server/plugin/auth/buildin/service_parser.go, server/plugin/auth/types.go, server/response/response.go, server/service/rbac/decision.go, server/service/rbac/rbac.go, server/service/rbac/resource.go
=> SCB-2176 Fix: targetResource label key not exist should be pass

server/resource/v4/auth_resource.go, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go
=> reduce client identity conflicts of ban list

server/handler/auth/auth.go, server/plugin/auth/buildin/buildin.go, server/resource/v4/auth_resource.go, server/resource/v4/auth_resource_test.go, server/service/rbac/context.go, server/service/rbac/context_test.go
=> SCB-2176 Fix: should not update or delete your own account info

datasource/etcd/role.go, datasource/mongo/role.go, datasource/role.go, go.mod, go.sum, pkg/errors/text.go, server/handler/auth/auth.go, server/resource/v4/auth_resource.go, server/resource/v4/role_resource.go, server/resource/v4/role_resource_test.go, server/service/rbac/dao/role_dao.go, server/service/rbac/dao/role_dao_test.go, server/service/rbac/decision.go, server/service/rbac/rbac.go, server/service/rbac/rbac_test.go, server/service/rbac/role.go
=> Add role manage error code

server/service/gov/kie/kie_distributor.go, server/service/gov/kie/validate.go
=> 添加创建业务场景未对alias字段校验，将对methods校验修改为method

server/service/rbac/account_dao.go, server/service/rbac/role_dao.go
=> SCB-2176 Fix: wrong quota error code

go.mod, go.sum, server/resource/v4/auth_resource.go, server/resource/v4/role_resource.go, server/service/rbac/account_dao.go, server/service/rbac/account_dao_test.go, server/service/rbac/authr_plugin.go, server/service/rbac/blocker.go, server/service/rbac/password.go, server/service/rbac/rbac.go, server/service/rbac/rbac_test.go, server/service/rbac/resource.go, server/service/rbac/role.go, server/service/rbac/role_dao.go, server/service/rbac/role_dao_test.go, server/service/validator/microservice_validator.go, server/service/validator/rbac_validator.go, server/service/validator/rbac_validator_test.go, server/service/validator/validator.go
1, Add new rbac error code.
2, param validator/ip ban moved from auth resource to rbac.
=> Add new rbac error code

server/service/rbac/role.go
=> Check role exist when init build in roles

server/service/rbac/password.go, server/service/rbac/rbac_test.go
=> change password force only when admin role change other users

README.md
=> SCB-2176 Update README

datasource/mongo/sd/indexc_test.go, datasource/mongo/types.go, docs/release/Readme.md, docs/release/releaseNotes-2.0.0.md, server/connection/hbws/websocket_test.go, server/resource/v4/role_resource_test.go, server/service/rbac/role_dao_test.go, server/service/validator/rbac_validator.go, syncer/plugins/servicecenter/transform_test.go, test/benchmark/login.sh
=> Add RAT Headers

go.sum, scripts/build/tools.sh, scripts/release/make_release.sh, scripts/release/start_scripts/darwin/start-service-center.sh
=> Fix: failed to startup with embedded etcd

docs/release/Readme.md, scripts/release/README.md, scripts/release/archive.sh
=> Update release README

datasource/mongo/event/instance_event_handler.go, datasource/mongo/sd/dep_cache.go, datasource/mongo/sd/instance_cache.go, datasource/mongo/sd/instancec_test.go, datasource/mongo/sd/mongo_cacher.go, datasource/mongo/sd/rule_cache.go, datasource/mongo/sd/service_cache.go, pkg/event/bus_service.go, server/handler/metrics/metrics.go
【issue】: #1046 
【特性/模块名称】：cache问题修复
【问题现象】：
1.实例属性更新未推送
2.服务，依赖关系频繁打印更新日志，未判定是否更新（list场景）
3.metric开关未使用
【修改内容】：
service，inst，dep增加新旧值更新判断
推送无订阅者情况下报错内容修改
metrics支持关闭
【自测情况】：ut全部通过
=> fix cache bugs

etc/conf/app.yaml, pkg/metrics/gatherer.go, pkg/metrics/manager.go, server/config/config.go, server/config/types.go, server/rest/metrics/prometheus.go, server/server.go
=> Nil point exception when disable metrics

server/resource/v4/auth_resource.go
=> Change the default duration of token expiration

datasource/account.go, datasource/datasource.go, datasource/etcd/account_lock.go, datasource/etcd/etcd.go, datasource/etcd/path/key_generator.go, datasource/manager.go, datasource/mongo/account_lock.go, datasource/mongo/mongo.go, datasource/options.go, etc/conf/app.yaml, server/server.go, server/service/account/account.go, server/service/account/account_test.go, server/service/rbac/authr_plugin.go, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go, server/service/rbac/password.go, test/test.go
=> add account lock to manage login failure

server/metrics/http.go
=> Change the logic of successful request metrics

Dockerfile.build, proxy.sh, scripts/build/tools.sh, scripts/docker/build-frontend-image/build.sh
=> Fix: can not build the frontend image

datasource/etcd/account.go, datasource/role_test.go
=> Fix: Can not delete the unused role after update account's role

server/core/config.go, server/core/proto/types.go, server/server.go
=> Change: Remove the microserivce auto clear mechanism

server/config/config.go
=> Fix: Security problem

datasource/etcd/ms.go, datasource/mongo/client/dao/microservice.go, datasource/mongo/metrics.go, datasource/mongo/ops.go, datasource/mongo/util/db.go, datasource/ms.go, server/plugin/quota/quota.go, server/service/quota/quota.go
=> Fix: Service/Instance Quota incorrect

datasource/account_test.go, datasource/mongo/account.go, datasource/mongo/client/model/types.go, datasource/mongo/role.go, datasource/mongo/util/db.go, datasource/role_test.go
=> Fix: no create/update time in list account/role response body

scripts/build/tools.sh
=> Add secure compile options

datasource/mongo/ms.go, datasource/mongo/util/db.go, integration/instances_test.go, server/rest/controller/v4/instance_controller.go, server/service/disco/instance_test.go
=> Fix: Can not discovery instances by service alias

server/service/gov/kie/kie_distributor.go
=> kie转换报错由fatal改为error。

server/service/gov/kie/kie_distributor.go
=> 修复编辑业务场景错误

scripts/build/tools.sh, ux/docker-compose.yml
=> Fix: sc not found in alpine

datasource/cache/ms_cache.go, datasource/etcd/etcd.go, datasource/etcd/ms.go, datasource/etcd/util/util.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/ms.go, datasource/options.go, datasource/schema_test.go, etc/conf/app.yaml, examples/dev/conf/app.yaml, pkg/util/context.go, server/config/config.go, server/config/server.go, server/server.go, server/service/disco/schema_test.go, test/test.go
=> [SCB-2294]Change: Modify schema without considering service environment

server/service/gov/kie/validate.go
=> 业务场景校验添加PATCH

go.mod, go.sum, pkg/errors/text.go, pkg/rest/util.go, server/plugin/auth/buildin/buildin.go, server/resource/v4/auth_resource.go, server/resource/v4/auth_resource_test.go, server/resource/v4/role_resource.go, server/service/rbac/perm_service.go, server/service/rbac/perm_service_test.go, server/service/rbac/rbac.go, server/service/rbac/resource.go
=> Feature: Add list self permission API

go.mod, go.sum, server/plugin/auth/buildin/buildin.go, server/resource/v4/auth_resource_test.go, server/service/rbac/account_service.go, server/service/rbac/authr_plugin.go, server/service/rbac/decision.go, server/service/rbac/init.go, server/service/rbac/password.go, server/service/rbac/resource.go
=> Change: DON'T check root exist if pass root token

server/plugin/auth/buildin/buildin.go, server/service/rbac/rbac.go
=> Optimize rbac code

datasource/account.go, datasource/account_test.go, datasource/etcd/account_lock.go, datasource/mongo/account_lock.go, docs/user-guides/rbac.md, server/resource/v4/auth_resource.go, server/resource/v4/auth_resource_test.go, server/service/account/account.go, server/service/account/account_test.go, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go, server/service/rbac/resource.go
=> Feature: Add list account lock API

datasource/account.go, datasource/etcd/account_lock.go, datasource/etcd/ms.go, datasource/etcd/util.go, datasource/mongo/account_lock.go, server/bootstrap/bootstrap.go, server/job/account/account.go, server/job/account/account_test.go, server/service/account/account.go
=> Fix: Account lock history never be remove

server/service/account/account.go, server/service/rbac/blocker.go, server/service/rbac/blocker_test.go
=> Feature: Save attempted status lock when auth failed

server/service/rbac/rbac.go
=> Fix: Should NOT auth health and version API

datasource/etcd/system.go, datasource/mongo/system.go, server/rest/admin/controller_v4.go, server/service/admin/admin.go, server/service/admin/dump.go, server/service/admin/dump_test.go
=> Optimize: Add Admin service

go.mod, go.sum, server/service/rbac/authr_plugin.go
=> 更新 golang-jwt 引用路径

go.mod, go.sum, server/plugin/auth/buildin/buildin.go, server/resource/v1/gov_resource.go, server/service/gov/config_distributor.go, server/service/gov/config_distributor_test.go, server/service/gov/kie/kie_distributor.go, server/service/gov/mock/mock.go, server/service/rbac/context.go, server/service/rbac/token/context.go
service-center cannot access the kie-client after rbac authentication is enabled for the kie
=> add sign request for kie-client

datasource/etcd/ms.go, datasource/mongo/engine.go, datasource/mongo/ms.go, datasource/ms.go, datasource/schema_test.go, datasource/service_test.go, pkg/proto/service.go, server/plugin/auth/buildin/service_parser.go, server/rest/controller/v4/microservice_controller.go, server/service/disco/metadata_dao.go, server/service/disco/microservice.go, server/service/disco/microservice_test.go, server/service/disco/schema_test.go
=> Optimize: Add discosvc.GetService

datasource/common.go, datasource/etcd/ms.go, datasource/etcd/util.go, datasource/instance_test.go, datasource/mongo/fast_register_test.go, datasource/mongo/mongo_test.go, datasource/mongo/ms.go, datasource/ms.go, etc/conf/app.yaml, pkg/validate/rule.go, server/plugin/quota/quota.go, server/service/disco/instance.go, server/service/disco/microservice.go, server/service/disco/schema.go
=> Change: Add the minimum interval of instance registration

server/plugin/auth/buildin/buildin.go, server/service/rbac/context.go
=> set a complete token

datasource/account.go
=> Fix: Return none when no locks

datasource/etcd/ms.go
=> Fix: show no consumers

server/service/gov/kie/kie_distributor.go
=> Fix: list gov failed when kie has no data

server/service/gov/kie/kie_distributor.go
=> add disabled situation

server/service/gov/kie/kie_distributor.go, server/service/rbac/context.go
=> Fix: add disabled situation

datasource/etcd/state/etcd/indexer_test.go, datasource/etcd/util/microservice_util.go, go.mod, go.sum, server/config/config.go, server/service/disco/instance_test.go
=> Fix: not correct log level when config initialization

datasource/etcd/event/dependency_event_handler.go, go.mod, pkg/util/net.go, pkg/util/net_test.go
=> Fix: Can not get the IPv6 remote addr

datasource/dep.go, datasource/dep_test.go, datasource/dependency_util.go, datasource/etcd/dep.go, datasource/etcd/event/dependency_event_handler.go, datasource/etcd/ms.go, datasource/etcd/util/dependency_util.go, datasource/etcd/util/dependency_util_test.go, datasource/mongo/dep.go, integration/apis.go, integration/microservices_test.go, pkg/proto/service.go, server/rest/controller/v4/dependency_controller.go, server/service/disco/dependency.go, server/service/disco/dependency_test.go, server/service/validator/dependency_validator.go, server/service/validator/validator.go
=> Fix: Add Dependency API

etc/conf/app.conf, server/plugin/registry/config.go, server/plugin/registry/etcd/etcd.go
=> Feature: add cluster member list check option

go.mod, go.sum, scripts/build/tools.sh, server/resource/gov/gov_resource.go
=> compatible kie-client error

docs/user-guides/metrics.md, server/metrics/meta.go, server/metrics/meta_reporter.go, server/metrics/meta_reporter_test.go, server/metrics/reporter.go, test/test.go
=> Optimize: Add service/instance usage metrics

datasource/ms_util.go, datasource/ms_util_test.go, docs/openapi/v4.yaml, go.mod, go.sum, integration/instances_test.go, server/rest/controller/v4/microservice_controller.go, server/service/disco/microservice.go, server/service/govern/graph.go
添加参数"withShared"，用于控制返回信息中是否包含共享服务，如SERVICECENTER。
用户场景：
当domain为default时，查询全量服务时除了返回用户的服务，还会返回共享服务如SERVICECENTER，共享服务用户并不关注，还会对用户造成一定干扰，因此默认不返回。
---
=> Add query parameter "withShared"

datasource/etcd/schema.go, datasource/manager.go, datasource/mongo/schema.go, datasource/schema/init.go, datasource/schema/options.go, datasource/schema/schema.go, etc/conf/app.yaml
当前契约是按照微服务版本一比一存储的，当升级微服务版本，较多场景下会冗余schema存储，导致后端数据存储暴涨
- hash：使用md5算法hash文件名与内容（要做接口抽象，以便后续切换算法），算出每个契约文件的“地址”，将地址作为etcd key，内容作为etcd value存储，不要做全量缓存，会把内存挤爆的，为了优化查询速度，只能做热点查询，比如就留1000size的契约缓存。
- 缓存：可以缓存{serviceid}/{schemaid}到hash(schemaid+schemacontent)的映射进行加速
- 存储结构：/cse-sr/ms/schema-content/{domain}/{project}/{schema_hash}，值为契约名字和内容
- 汇总查询：service的schemas slice应该存的是这些地址，需要汇总时，再进行关联查询
- **后台数据兼容：** 新老数据允许共存
- **rest API兼容：** 不新增rest API，不减少rest API，现有rest API语义全兼容
- **智能化判断：** 允许一个微服务版本部分schema是老逻辑，部分是新逻辑
---
=> Feature: Add schema ref

eventbase/bootstrap/bootstrap.go, eventbase/datasource/etcd/etcd.go, eventbase/datasource/etcd/etcd_test.go, eventbase/datasource/etcd/key/key.go, eventbase/datasource/etcd/task/task_dao.go, eventbase/datasource/etcd/task/task_dao_test.go, eventbase/datasource/etcd/tombstone/tombstone_dao.go, eventbase/datasource/etcd/tombstone/tombstone_dao_test.go, eventbase/datasource/manager.go, eventbase/datasource/mongo/client/client.go, eventbase/datasource/mongo/model/types.go, eventbase/datasource/mongo/mongo.go, eventbase/datasource/mongo/task/task_dao.go, eventbase/datasource/mongo/task/task_dao_test.go, eventbase/datasource/mongo/tombstone/tombstone_dao.go, eventbase/datasource/mongo/tombstone/tombstone_dao_test.go, eventbase/datasource/options.go, eventbase/datasource/tlsutil/tlsutil_test.go, eventbase/datasource/tombstone.go, eventbase/go.mod, eventbase/request/tombstone_request.go, eventbase/service/task/task_svc.go, eventbase/service/tombstone/tombstone_svc.go
【issue】：#1176
【修改内容】：
1. 新增新增 eventbase 用于对外暴露供使用
2. 添加bootstra用于一些文件初始化加载
3. 调整了event中的一些目录，因为再写syncer发现一些文件存放不合适导致循环依赖问题
【修改原因】：无
【影响范围】：无
【额外说明】：无
【测试用例】：都增加相关接口的测试用例，自测全部通过
=> [feat] add service in eventbase

datasource/etcd/retire.go, datasource/etcd/retire_test.go
=> #1183 Bug: can not retire the services which have dependencies

datasource/etcd/ms.go, datasource/etcd/path/key_convertor.go, datasource/etcd/path/key_generator.go, datasource/etcd/schema.go, datasource/etcd/sd/api.go, datasource/etcd/sd/schema.go, datasource/etcd/sd/types.go, datasource/etcd/util.go, datasource/etcd/util/util.go, datasource/mongo/mongo_test.go, datasource/mongo/ms.go, datasource/mongo/schema.go, datasource/schema/schema.go, datasource/schema/schema_test.go, datasource/schema_test.go, go.mod, go.sum, scripts/ut_test_in_docker.sh, server/plugin/quota/buildin/schema.go, server/plugin/quota/buildin/schema_test.go, server/resource/disco/schema_resource.go, server/resource/disco/schema_resource_test.go, server/rest/controller/v4/microservice_controller.go, server/service/disco/microservice.go, server/service/disco/microservice_test.go, server/service/disco/schema.go, server/service/disco/schema_test.go, server/service/govern/view_test.go, server/service/validator/schema_validator.go, server/service/validator/validator.go
=> Feature: Add schema ref, Part2 etcd/mongo implement

datasource/etcd/path/key_convertor.go, datasource/etcd/path/key_convertor_test.go, datasource/etcd/path/key_generator.go, datasource/etcd/retire.go, datasource/etcd/schema.go, datasource/mongo/retire.go, datasource/mongo/schema.go, datasource/retire.go, datasource/schema/schema.go, etc/conf/app.yaml, go.mod, go.sum, integration/instances_test.go, server/job/disco/retire.go, server/job/disco/schema.go, server/service/disco/retire_test.go, server/service/disco/schema_test.go
=> Feature: add schema retire cron job

datasource/etcd/dlock.go, server/job/disco/schema.go, server/job/disco/service.go, server/service/dlock/dlock.go, server/service/dlock/dlock_test.go
=> Bug: try dlock before start retirement job

datasource/etcd/account.go, datasource/etcd/account_test.go, datasource/etcd/task_util.go, datasource/etcd/tombstone_util.go, datasource/manager.go, go.mod, go.sum, test/test.go
【issue】#1196
【修改内容】：当开启同步时，创建、修改、删除 account 都会新增task，删除会新增tombstone
【修改原因】：无
【影响范围】：无
【额外说明】：无
【测试用例】：
开启同步任务：
1、创建一个account，删除该account，会创建2个task，以及一个tombstone
2、创建两个account，更新这两个，然后删除，会创建6个task，以及2个tombstone
=> [feat] add account sync func and ut

etc/conf/app.yaml, etc/conf/syncer.yaml, syncer/bootstrap/bootstrap.go, syncer/config/config.go, syncer/config/config_test.go, syncer/init/init.go, syncer/resource/admin/admin.go, syncer/resource/register.go, syncer/server/server.go
=> Feature: add syncer config framework

cmd/scserver/main.go, etc/conf/chassis.yaml, etc/conf/lager.yaml, etc/conf/microservice.yaml, etc/conf/syncer.yaml, server/core/core.go, server/server.go, syncer/config/config.go, syncer/init/init.go, syncer/rpc/server.go, syncer/server/server.go, syncer/service/admin/health.go
背景：之前syncer的server部分代码保留在sc逻辑中
方案：统一迁移到syncer下
---
=> Refactor: add syncer server

datasource/cache/ms_cache.go, datasource/etcd/ms.go, datasource/etcd/util/instance_util.go, datasource/instance_test.go, datasource/mongo/client/dao/instance.go, datasource/mongo/instance_util.go, datasource/mongo/ms.go, datasource/mongo/util/db.go, datasource/ms.go, server/service/disco/instance.go, server/service/disco/instance_test.go, server/service/validator/instance_validator.go, server/service/validator/rbac_validator.go, server/service/validator/validator.go
=> Feature: add put instance service

server/service/registry/registry.go, server/service/registry/registry_test.go
=> Bug: start up failed when upgrade sc version

etc/conf/app.yaml, server/api_server.go, server/core/microservice.go
背景：sc使用多网卡监听或域名注册场景，需要能指定自定义的实例的endpoint信息
---
=> Feature: support customize the sc registry endpoint

datasource/manager.go, go.sum, server/bootstrap/bootstrap.go
【issue】#1196
【修改内容】：
1、在 sc 启动初始化db的时候添加 evenbase 的初始化
【修改原因】：
1、sync同步功能
【影响范围】：无
【额外说明】：无
【测试用例】：无
=> [feat] add event initialization in sc

eventbase/go.mod, eventbase/go.sum, go.mod, go.sum
=> Bug: fix archaius GetBool bug

server/core/microservice.go, server/core/microservice_test.go, server/handler/context/context.go, server/service/registry/registry.go, server/service/sync/sync.go, syncer/rpc/server.go, syncer/service/sync/sync.go, test/test.go
=> Feature: sync the SC service

datasource/manager.go, eventbase/datasource/etcd/task/task_dao.go, eventbase/datasource/manager.go, eventbase/datasource/manager_test.go, eventbase/go.mod, eventbase/go.sum, eventbase/service/task/task_svc_test.go, eventbase/service/tombstone/tombstone_svc_test.go, syncer/service/task/manager.go, syncer/service/task/task.go, syncer/service/tombstone/tombstone_test.go, test/test.go
1. print error log when parse task
2. print task count info when load task
=> #1228 sync model  -- bug fix

syncer/service/admin/health.go, syncer/service/event/manager.go, syncer/service/task/manager.go
=> #1228 sync model - report metrics

datasource/manager.go, pkg/metrics/gatherer.go
=> Bug: not correct syncer metrics name

syncer/job/tombstone/tombstone.go
【issue】: #1212
【特性/模块名称】：删除过期的墓碑数据
【修改内容】：
Bugfix：修改获取删除墓碑数据定时时间
=> [feat] delete tombstone data

docs/dev-guides.rst, docs/dev-guides/quota.md, docs/index.rst, docs/plugin-tracing-guides.rst, docs/user-guides.rst, docs/user-guides/limits.md, docs/user-guides/quota.md
=> Add Quota management README

etc/conf/chassis.yaml, go.mod, go.sum, syncer/service/replicator/replicator.go, syncer/service/replicator/replicator_test.go
=> #1228 grpc syncer server supports 10M received size

datasource/etcd/account.go, datasource/mongo/account.go, server/service/rbac/account_service.go, syncer/service/replicator/resource/account.go, syncer/service/replicator/resource/account_test.go, syncer/service/task/manager.go
=> #1228 account use dao to crud

syncer/service/replicator/resource/account.go, syncer/service/replicator/resource/instance.go, syncer/service/replicator/resource/kv.go, syncer/service/replicator/resource/kv_test.go, syncer/service/replicator/resource/microservice.go, syncer/service/replicator/resource/resource.go, syncer/service/replicator/resource/resource_test.go, syncer/service/replicator/resource/role.go, syncer/service/task/manager.go
=> #1228 support kv timestamp

eventbase/datasource/etcd/key/key.go
【issue】 #1212 
【特性/模块名称】：删除过期的墓碑数据
【修改内容】：
Bugfix：修改墓碑数据的key
=> [feat] fix delete tombstone data bug

syncer/service/replicator/resource/account.go, syncer/service/task/manager.go
=> #1228 update accout failed, make panic

datasource/etcd/ms.go, datasource/etcd/util.go, datasource/mongo/dao/microservice.go, datasource/mongo/microservice_util.go, datasource/mongo/ms.go, datasource/ms.go, datasource/service_test.go, server/service/disco/metadata.go, server/service/govern/view.go, server/service/govern/view_test.go
=> Bug: govern api return empty schemaIds

syncer/service/event/manager.go, syncer/service/event/manager_test.go, syncer/service/replicator/replicator_test.go, syncer/service/replicator/resource/heartbeat.go, syncer/service/replicator/resource/heartbeat_test.go, syncer/service/replicator/resource/instance.go, syncer/service/replicator/resource/instance_test.go, syncer/service/replicator/resource/resource.go
=> #1228 replica instance failed, resend again

syncer/service/replicator/resource/role.go, syncer/service/replicator/resource/role_test.go
=> #1228 replica role use dao

syncer/service/replicator/resource/instance.go
=> Bug: overwrite the instance properties when replicator sync heartbeat

server/config/config.go, syncer/service/replicator/replicator.go, syncer/service/replicator/resource/instance.go, syncer/service/replicator/resource/instance_test.go
=> #1228 replica instance fail when service not exist, resend again

syncer/service/event/manager.go, syncer/service/replicator/resource/instance.go
=> #1228 bug: replica instance fail when service not exist, resend again

syncer/service/admin/health.go
【issue】:#1206
【修改内容】：sync 包的health 接口，修改 调用rpc方式
复用client conn
【修改原因】：client conn 不用每次调用new 一个
【影响范围】：无
【额外说明】：无
【测试用例】：无
=> [feat] fix gRpc client conn

datasource/etcd/etcd.go, datasource/etcd/ms.go, datasource/etcd/util.go, datasource/mongo/mongo.go, datasource/mongo/ms.go, datasource/options.go, datasource/schema_test.go, etc/conf/app.yaml, examples/dev/conf/app.yaml, server/config/config.go, server/config/server.go, server/core/microservice.go, server/server.go
背景：契约是否可编辑，依赖微服务环境的具体定义，但service-center本身对微服务环境的定义是开放的，契约是否可编辑不应该是service-center的考虑范围，而是使用方需要考虑的。
---
=> Change: remove the option 'SchemaNotEditable'

go.mod, go.sum
背景：sc的eventbase包相对稳定，需切换成版本依赖方式，不再使用replace，以便其他项目集成sc的源码做二次开发
---
=> Optimize: clean go.mod file

docs/release/Readme.md, docs/release/releaseNotes-2.1.0.md
【修改内容】：
1、在 release 的 Readme 中新增 add tag
2、新增版本发布邮件投票格式
【修改原因】：release 的 readme 文档缺少打tag；版本发布投票格式
【影响范围】：无
【额外说明】：无
【测试用例】：无需修改测试用例
=> [doc] update the release Readme.md

syncer/service/admin/health.go
=> Bug fix: syncer peer metrics are not correct

server/service/validator/rbac_validator.go, server/service/validator/rbac_validator_test.go
=> Bug fix: allow blank account/role name

benchmark/READM.md, benchmark/find/find_1000_intance.js, benchmark/find/find_100_intance.js, benchmark/find/find_one_intance.js, benchmark/register/hb_same_service.js, benchmark/register/register_random_service.js, benchmark/register/register_same_service.js
=> add benchmark for different deploy topology

go.mod, go.sum, syncer/service/replicator/resource/config.go
=> [feat]upgrade kie version

frontend/server/server_test.go
=> [fix]frontend UT failure

README.md, docs/get-started/install.md
=> update doc, support kitex now

server/service/gov/kie/kie_distributor.go, server/service/gov/kie/validate.go, server/service/gov/mock/mock.go
=> [feat]support fault injection governance policy

server/service/gov/kie/kie_distributor.go, server/service/gov/mock/mock.go
=> [feat]support loadbalancer governance policy

Dockerfile.build, benchmark/READM.md, benchmark/find/find_1000_intance.js, benchmark/find/find_100_intance.js, benchmark/find/find_one_intance.js, benchmark/register/hb_same_service.js, benchmark/register/register_random_service.js, benchmark/register/register_same_service.js, scripts/build/tools.sh, scripts/ut.sh
=> revise benchmark report

syncer/rpc/server.go, syncer/service/admin/health.go
=> [fix]syncer health failure

go.mod, go.sum
=> [feat]Upgrade 3rd party version

server/ext/policy/buitin.go, server/resource/gov/gov_resource_test.go, server/service/grc/kie/kie_distributor.go, server/service/grc/mock/mock.go
=> [fix]typo load balance policy name

syncer/service/replicator/resource/config.go
问题现象：2个互相同步的kie实例，在一端修改了配置，另一端查看发现kv存在，但查看history接口却是空的
修复方案：在同步逻辑中增加kie的处理机制，写入history记录
---
=> [fix]sync config without history

pkg/util/util.go, pkg/util/util_test.go, server/resource/gov/gov_resource_test.go, server/service/grc/config_distributor.go, server/service/grc/kie/kie_distributor.go
=> [fix]gov list return wrong kind

syncer/service/replicator/replicator.go, syncer/service/replicator/resource/config.go
=> [fix]syncer log print typo

server/service/rbac/account_service.go, server/service/rbac/account_service_test.go
背景：当前帐号ID是随机UUID生成，存在一个场景，在导入已有帐号时希望能指定一个有意义的ID与其他帐号系统做关联
---
=> Change: allow creating account with ID

go.mod, go.sum, pkg/util/util.go, pkg/util/util_test.go, server/service/rbac/account_service.go, server/service/rbac/account_service_test.go, test/test.go
=> Change: allow batch create account without password

syncer/service/replicator/replicator.go, syncer/service/replicator/resource/resource.go
=> 添加日志，用于双集群引擎同步debug

syncer/service/event/manager.go, syncer/service/replicator/resource/config.go
=> 用于双集群引擎同步debug

syncer/service/task/manager.go
=> 用于双集群引擎同步debug-v2

syncer/service/task/manager.go
=> 用于双集群引擎同步debug-v4

datasource/etcd/role.go, datasource/etcd/role_test.go, datasource/mongo/role.go, datasource/rbac/role.go, server/service/rbac/permission.go, server/service/rbac/rbac.go, server/service/rbac/resource.go, server/service/rbac/role_service.go
sc 治理接口转发到KIE透传Authorization 头
=> Change:  add old role migrate function, old role has config permission default

pkg/privacy/password.go, pkg/privacy/password_test.go
=> [feat]RBAC帐号password加密算法支持自定义扩展

pkg/privacy/password_test.go, server/service/rbac/rbac.go, server/service/rbac/rbac_test.go
当前Login接口，每次访问都会重新解密RSA私钥信息，性能低下
---
=> [fix]bad performance in login API

etc/conf/app.conf, frontend/Readme.md, frontend/schema/schemahandler.go, frontend/server/config.go, frontend/server/server.go, server/service/govern/view.go
=> [fix]frontend SSRF

pkg/dump/dump.go, server/service/admin/dump.go
=> [fix]server information leak in dump API

README.md, ux/docker-compose.yml
=> [fix] start UX failed

integration/apis.go, integration/instances_test.go, integration/syncer_test.go, scripts/integration_test.sh, server/core/core.go, server/pubsub/ws/websocket_test.go, server/server.go, server/service/admin/dump_test.go, server/service/heartbeat/websocket_test.go, syncer/bootstrap/bootstrap.go, syncer/server/server.go, syncer/service/admin/health.go, syncer/service/sync/sync.go, syncer/service/task/lock.go
=> [fix] syncer init failed

datasource/etcd/ms.go, datasource/mongo/ms.go, datasource/ms.go, server/resource/disco/instance_resource.go, server/service/disco/instance.go
=> multi instances change status by properties

go.mod, go.sum, server/service/grc/kie/kie_distributor.go
=> 增加优先级字段，支持优先级排序

server/plugin/auth/buildin/buildin.go
=> check api before authenticate the request

.github/workflows/golangci-lint.yml, datasource/etcd/ms.go, datasource/local/bootstrap/bootstrap.go, datasource/local/schema.go, datasource/schema/init.go, datasource/schema/schema.go, integration/microservices_test.go, server/bootstrap/bootstrap.go, server/config/config.go, server/config/server.go, server/service/disco/schema.go
store schemas by local storage
=> store schemas by local storage

server/config/config.go
=> [feat] support the size of log up to 500M

server/plugin/auth/buildin/buildin.go
=> [fix] fix switch type

server/service/registry/registry.go, syncer/service/replicator/resource/config.go, syncer/service/replicator/resource/resource.go, syncer/service/task/manager.go
=> fix some problems

datasource/common.go, datasource/etcd/ms.go, datasource/etcd/ops.go, datasource/etcd/path/key_generator.go, datasource/etcd/sd/api.go, datasource/etcd/sd/types.go, datasource/etcd/util/environment_util.go, datasource/etcd/util/microservice_util.go, datasource/etcd/value/parser.go, datasource/mongo/ms.go, datasource/mongo/ops.go, datasource/ms.go, go.mod, go.sum, server/plugin/quota/buildin/buildin.go, server/plugin/uuid/buildin/buildin.go, server/plugin/uuid/uuid.go, server/resource/disco/environment_resource.go, server/resource/register.go, server/service/disco/environment.go, server/service/disco/metadata.go, server/service/quota/environment.go, server/service/validator/environment_validator.go, server/service/validator/microservice_validator.go, syncer/service/replicator/resource/environment.go, syncer/service/replicator/resource/instance.go, syncer/service/replicator/resource/resource.go
=> [fea] service-center support the feature of manage environments

server/api_server.go, server/service/disco/metadata.go, server/service/registry/registry.go
=> [fix] fix the problem that selfregustry will be refused

datasource/etcd/ms.go, datasource/etcd/path/key_generator.go
=> [fix] fix the problem that use environment name

datasource/etcd/ms.go, datasource/etcd/util/environment_util.go, server/service/disco/environment.go, server/service/disco/metadata.go, server/service/registry/registry.go, server/service/validator/microservice_validator.go
=> [fix] fix some environment problems

datasource/common.go, datasource/etcd/ms.go, datasource/etcd/path/key_generator.go, datasource/mongo/ms.go, datasource/mongo/ops.go, go.mod, go.sum, server/resource/disco/environment_resource.go, syncer/service/replicator/resource/environment.go
=> [fix] modify some error reponse in some error situation

syncer/service/replicator/resource/environment.go
=> [fix] fix env info will not be synced [can not load current resource]
